/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;
import principal.Principal;

/**
 *
 * @author gcoaquira
 */
public class CarnetBecario extends javax.swing.JFrame {

    /**
     * Creates new form CarnetBecario
     */
    public CarnetBecario() {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/imagenes/iconoCod.png")).getImage());
        this.setLocationRelativeTo(null);

        
        txtcodigoE.setText(pnlEstudiantes.VCodigo);
        txtdniE.setText(pnlEstudiantes.VDni);
        txtnombresE.setText(pnlEstudiantes.VNombre);
        txtapellidosE.setText(pnlEstudiantes.VApellidos);
        txtfacultadE.setText(pnlEstudiantes.VFacultad);
        txtescuelaE.setText(pnlEstudiantes.VEscuela);
        txtcodigoE.setText(pnlEstudiantes.VCodigo+"");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtcodigoE = new javax.swing.JTextField();
        txtdniE = new javax.swing.JTextField();
        txtnombresE = new javax.swing.JTextField();
        txtapellidosE = new javax.swing.JTextField();
        txtfacultadE = new javax.swing.JTextField();
        txtescuelaE = new javax.swing.JTextField();
        codigo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnCerrar = new rscomponentshade.RSButtonShade();
        btnImprimir = new rscomponentshade.RSButtonShade();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(null);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtcodigoE.setEditable(false);
        txtcodigoE.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtcodigoE.setForeground(new java.awt.Color(255, 255, 255));
        txtcodigoE.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtcodigoE.setBorder(null);
        txtcodigoE.setOpaque(false);
        txtcodigoE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcodigoEKeyReleased(evt);
            }
        });
        getContentPane().add(txtcodigoE, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 210, 33));

        txtdniE.setEditable(false);
        txtdniE.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtdniE.setBorder(null);
        txtdniE.setOpaque(false);
        getContentPane().add(txtdniE, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 185, 20));

        txtnombresE.setEditable(false);
        txtnombresE.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtnombresE.setBorder(null);
        txtnombresE.setOpaque(false);
        getContentPane().add(txtnombresE, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 185, 20));

        txtapellidosE.setEditable(false);
        txtapellidosE.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtapellidosE.setBorder(null);
        txtapellidosE.setOpaque(false);
        getContentPane().add(txtapellidosE, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 185, 20));

        txtfacultadE.setEditable(false);
        txtfacultadE.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtfacultadE.setBorder(null);
        txtfacultadE.setOpaque(false);
        getContentPane().add(txtfacultadE, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 185, 20));

        txtescuelaE.setEditable(false);
        txtescuelaE.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtescuelaE.setBorder(null);
        txtescuelaE.setOpaque(false);
        getContentPane().add(txtescuelaE, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 185, 20));

        codigo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 73, 160, 160));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/carnet.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 4, 510, 310));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        btnCerrar.setBackground(new java.awt.Color(10, 36, 95));
        btnCerrar.setText("Cerrar");
        btnCerrar.setBgHover(new java.awt.Color(10, 36, 95));
        btnCerrar.setBgShade(new java.awt.Color(255, 255, 255));
        btnCerrar.setBgShadeHover(new java.awt.Color(242, 187, 10));
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        btnImprimir.setBackground(new java.awt.Color(10, 36, 95));
        btnImprimir.setText("Imprimir");
        btnImprimir.setBgHover(new java.awt.Color(10, 36, 95));
        btnImprimir.setBgShade(new java.awt.Color(255, 255, 255));
        btnImprimir.setBgShadeHover(new java.awt.Color(242, 187, 10));
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(296, Short.MAX_VALUE)
                .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 510, 70));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtcodigoEKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcodigoEKeyReleased

        if (this.txtcodigoE.getText().length() > 0) {
            iconoSys = qr.createQR(this.txtcodigoE.getText(), 220, colorp, colors);
            ImageIcon QR = new ImageIcon(iconoSys);
            this.codigo.setIcon(QR);
            //            iconoSys = qr.createQR(this.texto.getText(), 500);
        } else {
            iconoSys = null;
            this.codigo.setIcon(null);
        }
    }//GEN-LAST:event_txtcodigoEKeyReleased

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        
        dispose();
        
        
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnImprimirActionPerformed
public void setEjecuar()
     {
         qr();
         
     }
Color colorp = Color.white, colors = Color.black;
MyQRCreator qr = new MyQRCreator();
BufferedImage iconoSys = null;public void qr()
    {
           if (this.txtcodigoE.getText().length() > 0) {
            iconoSys = qr.createQR(this.txtcodigoE.getText(), 220, colorp, colors);
            ImageIcon QR = new ImageIcon(iconoSys);
            this.codigo.setIcon(QR);
            //            iconoSys = qr.createQR(this.texto.getText(), 500);
        } else {
            iconoSys = null;
            this.codigo.setIcon(null);
        }
    }
    
    private void secundarioActionPerformed(java.awt.event.ActionEvent evt) {                                           
        if (iconoSys == null) {
            JOptionPane.showMessageDialog(this, "Debe generar un código QR\npara usar los colores.", "No genero código", 0,
                    new ImageIcon(getClass().getResource("/imagenes/msj_info.png")));
        } else {
            Color colorT = colors;
            JColorChooser ventanaDeColores = new JColorChooser();
            colors = ventanaDeColores.showDialog(this, "Seleccione un Color", Color.black);

            if (colors != null) {

                iconoSys = new BufferedImage(220, 220, BufferedImage.TYPE_INT_RGB);
                iconoSys.createGraphics();
                Graphics2D graphics = (Graphics2D) iconoSys.getGraphics();
                graphics.setColor(colorp);
                graphics.fillRect(0, 0, 220, 220);
                graphics.setColor(colors);

                for (int i = 0; i < 220; i++) {
                    for (int j = 0; j < 220; j++) {
                        if (MyQRCreator.matrix.get(i, j)) {
                            graphics.fillRect(i, j, 1, 1);
                        }
                    }
                }

                ImageIcon QR = new ImageIcon(iconoSys);
                this.codigo.setIcon(QR);
            } else {
                colors = colorT;
            }
        }
    } 
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarnetBecario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarnetBecario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarnetBecario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarnetBecario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CarnetBecario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rscomponentshade.RSButtonShade btnCerrar;
    private rscomponentshade.RSButtonShade btnImprimir;
    private javax.swing.JLabel codigo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtapellidosE;
    private javax.swing.JTextField txtcodigoE;
    private javax.swing.JTextField txtdniE;
    private javax.swing.JTextField txtescuelaE;
    private javax.swing.JTextField txtfacultadE;
    private javax.swing.JTextField txtnombresE;
    // End of variables declaration//GEN-END:variables
}
