/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.image.BufferedImage;
import java.util.concurrent.Executor;
import java.util.concurrent.Executors;
import java.util.concurrent.ThreadFactory;

import com.github.sarxos.webcam.Webcam;
import com.github.sarxos.webcam.WebcamPanel;
import com.github.sarxos.webcam.WebcamResolution;
import com.google.zxing.BinaryBitmap;
import com.google.zxing.LuminanceSource;
import com.google.zxing.MultiFormatReader;
import com.google.zxing.NotFoundException;
import com.google.zxing.Result;
//import com.google.zxing.client.j2se.BufferedImageLuminanceSource;
import com.google.zxing.client.j2se.BufferedImageLuminanceSource;
import com.google.zxing.common.HybridBinarizer;
import java.awt.Container;
import static java.awt.Frame.ICONIFIED;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

import Entidad.ClsEntInvitados;
import Negocio.ClsNegInvitados;
import Entidad.ClsEntEstudiante;
import Negocio.ClsNegEstudiante;

import Entidad.ClsEntAsistentes;
import Negocio.ClsNegAsistentes;

import Entidad.ClsEntEvento;
import Negocio.ClsNegEvento;
import Entidad.ClsEntFacultadInvitada;
import Negocio.ClsNegFacultdadInvitada;
import java.awt.MouseInfo;
import java.awt.Point;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import static paneles.pnlIniciarEvento.rs;

/**
 *
 * @author usuario
 */
public class FrmTomarAsistencia extends javax.swing.JFrame implements Runnable, ThreadFactory {

    static ResultSet rs = null;
    int x, y;

    private static final long serialVersionUID = 6441489157408381878L;
//private Executor executor = Executors.newSingleThreadExecutor((ThreadFactory) this);
    private Executor executor = Executors.newSingleThreadExecutor(this);
    private Webcam webcam = null;
    private WebcamPanel panel = null;
    private JTextField txt = null;
    private JPanel panel1;

    /**
     * Creates new form FrmTomarAsistencia
     */

    public void cerrar() {
        Object[] opciones = {"Aceptar", "Cancelar"};
        int eleccion = JOptionPane.showOptionDialog(rootPane, "En realidad desea salir del Sistema?", "SISTEMA",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE, null, opciones, "Aceptar");
        if (eleccion == JOptionPane.YES_OPTION) {

            dispose();
        } else {
        }
    }

    public FrmTomarAsistencia() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setLocationRelativeTo(this);

        cargarcomEventos();
        //   txtingreso.setText(""+getHoraActual());
        txthE1.setVisible(false);
        txthS1.setVisible(false);
        txtidescuela.setVisible(false);
        jButton2.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        rSLabelHoraBeanInfo1 = new rojeru_san.RSLabelHoraBeanInfo();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txtnombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtcodiigo = new javax.swing.JTextField();
        txtescuela = new javax.swing.JTextField();
        txtfacultad = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txthE1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        txthS1 = new javax.swing.JTextField();
        txtidescuela = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblasis = new javax.swing.JTable();
        cboeventos = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        btnActivarCamara = new rscomponentshade.RSButtonShade();
        btnSalir = new rscomponentshade.RSButtonShade();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtingreso = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtsalida = new javax.swing.JTextField();
        rSLabelFecha1 = new rojeru_san.RSLabelFecha();
        jLabel1 = new javax.swing.JLabel();
        rSLabelHora1 = new rojeru_san.RSLabelHora();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setFocusableWindowState(false);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(242, 187, 10));

        jPanel6.setBackground(new java.awt.Color(10, 36, 95));
        jPanel6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel6MouseDragged(evt);
            }
        });
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel6MousePressed(evt);
            }
        });
        jPanel6.setLayout(new java.awt.GridBagLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("CONTROL DE ASISTENCIA DE BECARIOS");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 37;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 82, 14, 86);
        jPanel6.add(jLabel4, gridBagConstraints);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1286, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        txtnombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("NOMBRE ALUMNO");

        txtescuela.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtfacultad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("FACULTAD");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("ESCUELA");

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtescuela, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfacultad, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(txthE1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txthS1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtidescuela, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtcodiigo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(jLabel7)
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtfacultad, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtescuela, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txthE1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txthS1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtidescuela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtcodiigo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        tblasis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblasis);

        cboeventos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboeventos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboeventosActionPerformed(evt);
            }
        });

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 318, Short.MAX_VALUE)
        );

        btnActivarCamara.setBackground(new java.awt.Color(6, 20, 51));
        btnActivarCamara.setText("Activar Cámara");
        btnActivarCamara.setBgHover(new java.awt.Color(10, 36, 95));
        btnActivarCamara.setBgShade(new java.awt.Color(255, 255, 255));
        btnActivarCamara.setBgShadeHover(new java.awt.Color(242, 187, 10));
        btnActivarCamara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActivarCamaraActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(6, 20, 51));
        btnSalir.setText("Salir");
        btnSalir.setBgHover(new java.awt.Color(10, 36, 95));
        btnSalir.setBgShade(new java.awt.Color(255, 255, 255));
        btnSalir.setBgShadeHover(new java.awt.Color(242, 187, 10));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/beca18.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 51));
        jLabel2.setText("INGRESO");

        txtingreso.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setText("SALIDA");

        txtsalida.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        rSLabelFecha1.setForeground(new java.awt.Color(10, 36, 95));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/upt.png"))); // NOI18N

        rSLabelHora1.setForeground(new java.awt.Color(0, 0, 153));
        rSLabelHora1.setFont(new java.awt.Font("Roboto Bold", 1, 36)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rSLabelFecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtingreso, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(100, 100, 100)
                                        .addComponent(txtsalida, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rSLabelHora1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addGap(155, 155, 155)
                                                .addComponent(jLabel3))))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnActivarCamara, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                    .addComponent(cboeventos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(84, 84, 84))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addComponent(rSLabelFecha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addComponent(rSLabelHora1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(22, 22, 22)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtingreso, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtsalida, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnActivarCamara, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cboeventos, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
  Container content = getContentPane();
    private void txtnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreActionPerformed

    }//GEN-LAST:event_txtnombreActionPerformed

    public void activarcamara() {
        //activarcamara();
        //  content.enable(true);
        Container content = getContentPane();
        content.setLayout(new FlowLayout());

        FlowLayout layout = new FlowLayout(FlowLayout.LEFT, 8, 5);

        Dimension size = WebcamResolution.QVGA.getSize();

        webcam = Webcam.getWebcams().get(0);
        webcam.setViewSize(size);

        panel = new WebcamPanel(webcam);
        //  panelNormal=new  WebcamPanel(webcam);
        panel.setPreferredSize(size);
        panel.setFPSDisplayed(true);
        panel.setSize(400, 300);
        panel.setLocation(780, 100);
        panel.setVisible(true);

        content.add(panel);

        content.setLayout(null);
        setVisible(true);
        //  executor.execute(this);
        executor.execute((Runnable) this);

    }
    private void cboeventosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboeventosActionPerformed
        // TODO add your handling code here:
        buscar();

    }//GEN-LAST:event_cboeventosActionPerformed
    public void limpiarcajas() {
        txtnombre.setText("");
        txtfacultad.setText("");
        txtescuela.setText("");
        txtcodiigo.setText("");
        //   txtcodiigo
        txtidescuela.setText("");
        txtingreso.setText("");
        txtsalida.setText("");
    }
    private void jPanel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jPanel6MousePressed

    private void jPanel6MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseDragged
        Point mueve = MouseInfo.getPointerInfo().getLocation();
        this.setLocation(mueve.x - x, mueve.y - y);
    }//GEN-LAST:event_jPanel6MouseDragged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        cerrar();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnActivarCamaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActivarCamaraActionPerformed
        // TODO add your handling code here:
        activarcamara();
    }//GEN-LAST:event_btnActivarCamaraActionPerformed

    public void buscar() {
        String titulo[] = {"codigo", "hora E", "Hora S"};

        ClsNegInvitados consumos = new ClsNegInvitados();
//import Entidad.ClsEntInvitados;
//import Negocio.ClsNegInvitados;
        ArrayList<ClsEntInvitados> empleado = consumos.ListarIvitadosAEvento(idper[cboeventos.getSelectedIndex()]);
        //  JOptionPane.showMessageDialog(null,idper[cboeventos.getSelectedIndex()]);
        Iterator iterator = empleado.iterator();
        DefaultTableModel dtm = new DefaultTableModel(null, titulo);

        String columna[] = new String[5];
        while (iterator.hasNext()) {
            ClsEntInvitados Asis = new ClsEntInvitados();
            Asis = (ClsEntInvitados) iterator.next();
            columna[0] = String.valueOf(Asis.getId_estu());
            columna[1] = Asis.getHoraE();
            columna[2] = Asis.getHoraS();
            dtm.addRow(columna);
        }
//
        tblasis.setModel(dtm);
    }

    public void run() {
        try {
            do {
                try {
                    Thread.sleep(100);
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
                Result result = null;
                BufferedImage image = null;
                if (webcam.isOpen()) {
                    if ((image = webcam.getImage()) == null) {
                        continue;
                    }
                    LuminanceSource source = new BufferedImageLuminanceSource(image);
                    BinaryBitmap bitmap = new BinaryBitmap(new HybridBinarizer(source));
                    try {
                        result = new MultiFormatReader().decode(bitmap);
                    } catch (NotFoundException e) {
                        // fall thru, it means there is no QR code in image
                    }
                }
                if (result != null) {
                    txtcodiigo.setText(result.getText());
                    txtingreso.setText("" + getHoraActual());
                    int Busqueda;
                    Busqueda = Integer.parseInt(txtcodiigo.getText());
                    boolean encuentra = false;
                    ClsNegInvitados Escuela = new ClsNegInvitados();
                    try {
                        rs = Escuela.ConsultarInvitados2(idper[cboeventos.getSelectedIndex()], Busqueda);
                        while (rs.next()) {
                            txtnombre.setText((String) rs.getString(2));
                            txtescuela.setText((String) rs.getString(3));
                            txtfacultad.setText((String) rs.getString(6));
                            txthE1.setText((String) rs.getString(4));
                            txthS1.setText((String) rs.getString(5));
                            txtidescuela.setText((String) rs.getString(7));
                            if (!txthE1.getText().equals("")) {
                                txtingreso.setText((String) rs.getString(4));
                            }
                            if (!txthE1.getText().equals("") && !txthS1.getText().equals("")) {
                                JOptionPane.showMessageDialog(null, "ya tienes ingreso y salida chau");
                                limpiarcajas();
                                //    Container content = getContentPane();
                                //   content.enable(false);
                                webcam.close();
                                activarcamara();
                                return;
                            }

                            encuentra = true;
                            if (txthE1.getText().equals("")) {
                                //   JOptionPane.showMessageDialog(null,"ya ha ingresaso");
                                int codigo;
                                codigo = Integer.parseInt(txtcodiigo.getText());
                                //MODIFICANDO LA HORA DE INGRESO
                                ClsEntInvitados o = new ClsEntInvitados();
                                ClsNegInvitados ob = new ClsNegInvitados();
                                o.setId_estu(codigo);
                                o.setHoraE(txtingreso.getText());
                                ob.ModificarAsistenteEntrada(idper[cboeventos.getSelectedIndex()], codigo, o);
                                // cargarcomEventos();
                                buscar();
                                JOptionPane.showMessageDialog(null, "REgsitrado");
                                limpiarcajas();
                                webcam.close();
                                activarcamara();

                            } else {
                                //JOptionPane.showMessageDialog(null,"va a marcar su salida");
                                //   txtingreso.setText((String)rs.getString(4));
                                //MODIFICANDO HORA DE SALIDA
                                txtsalida.setText("" + getHoraActual());
                                int codigo;
                                ClsEntInvitados o = new ClsEntInvitados();
                                ClsNegInvitados ob = new ClsNegInvitados();
                                codigo = Integer.parseInt(txtcodiigo.getText());
                                o.setId_estu(codigo);
                                o.setHoraS(txtsalida.getText());
                                ob.ModificarAsistenteSalida(idper[cboeventos.getSelectedIndex()], codigo, o);
                                //cargarcomEventos();
                                buscar();
                                JOptionPane.showMessageDialog(null, "REgsitrado sALIDA");
                                // GuardarAsistencia();

                                ClsEntAsistentes obje = new ClsEntAsistentes();
                                ClsNegAsistentes obneg = new ClsNegAsistentes();
                                obje.setId_eve(idper[cboeventos.getSelectedIndex()]);
                                obje.setCodigo_estu(Integer.parseInt(txtcodiigo.getText()));
                                obje.setId_escu(Integer.parseInt(txtidescuela.getText()));
                                obje.setHora_entrada(txthE1.getText());
                                obje.setHora_salida0(txtsalida.getText());

                                obneg.AgregarAsistentes2(obje);
                                limpiarcajas();
                                webcam.close();
                                activarcamara();
                            }
                        }
                        if (encuentra == false) {
                            JOptionPane.showMessageDialog(null, "No estas en La Lista Wey");
                        }

                    } catch (Exception ex) {
                        ex.printStackTrace();
                    }
//                                
//                                int Busqueda;
//                                Busqueda= Integer.parseInt(txtcodiigo.getText());        
//                                ClsNegEstudiante Estu = new ClsNegEstudiante();
//
//                                try{
//
//                                    rs=Estu.ConsultarEstudiante2(Busqueda);
//                                    boolean encuentra =false;
//                                    while(rs.next()){
//                                        txtnombre.setText((String) rs.getString(2));
//                                      //  txtidescuela.setText((String)rs.getString(3));
//                                        txtescuela.setText((String)rs.getString(4));
//                                        encuentra= true;
//
//                                    }
//                                    if(encuentra== false){
//                                        JOptionPane.showMessageDialog(null,"No existen registros","Tabla Consultas",1);
//                                    }
//
//                                }catch(Exception ex){
//                                    ex.printStackTrace();
//                                }
//                                
                }
//                        else {
//                            JOptionPane.showMessageDialog(null,"codigo no reconocido");
//                        }

            } while (true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "codigo no reconocido");
            webcam.close();
            activarcamara();
        }

    }

    public void GuardarAsistencia() {
        ClsEntAsistentes obje = new ClsEntAsistentes();
        ClsNegAsistentes obneg = new ClsNegAsistentes();
        obje.setId_eve(idper[cboeventos.getSelectedIndex()]);
        obje.setCodigo_estu(Integer.parseInt(txtcodiigo.getText()));
        obje.setId_escu(Integer.parseInt(txtidescuela.getText()));
        obje.setHora_entrada(txthE1.getText());
        obje.setHora_salida0(txtsalida.getText());

        obneg.AgregarAsistentes(obje);

    }

    int intcontador;
    int idper[] = new int[100];

    void cargarcomEventos() {
        ClsNegEvento Evento = new ClsNegEvento();
        ArrayList<ClsEntEvento> Eve = Evento.ListarEvento();
        Iterator iterator = Eve.iterator();
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();

        modelo.removeAllElements();

        String columna[] = new String[3];
        intcontador = 0;
        while (iterator.hasNext()) {
            ClsEntEvento Even = new ClsEntEvento();
            Even = (ClsEntEvento) iterator.next();
            idper[intcontador] = Even.getId_eve();
            columna[0] = String.valueOf(Even.getId_eve());
            columna[1] = Even.getTitulo_eve();
            modelo.addElement(Even.getTitulo_eve());
            intcontador++;
        }
        cboeventos.setModel(modelo);
    }

    public static String getHoraActual() {
        Date ahora = new Date();
        SimpleDateFormat formateador = new SimpleDateFormat("hh:mm:ss");
        return formateador.format(ahora);
    }

    public Thread newThread(Runnable r) {
        Thread t = new Thread(r, "example-runner");
        t.setDaemon(true);
        return t;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTomarAsistencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTomarAsistencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTomarAsistencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTomarAsistencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTomarAsistencia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rscomponentshade.RSButtonShade btnActivarCamara;
    private rscomponentshade.RSButtonShade btnSalir;
    private javax.swing.JComboBox<String> cboeventos;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private rojeru_san.RSLabelFecha rSLabelFecha1;
    private rojeru_san.RSLabelHora rSLabelHora1;
    private rojeru_san.RSLabelHoraBeanInfo rSLabelHoraBeanInfo1;
    private javax.swing.JTable tblasis;
    private javax.swing.JTextField txtcodiigo;
    private javax.swing.JTextField txtescuela;
    private javax.swing.JTextField txtfacultad;
    private javax.swing.JTextField txthE1;
    private javax.swing.JTextField txthS1;
    private javax.swing.JTextField txtidescuela;
    private javax.swing.JTextField txtingreso;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtsalida;
    // End of variables declaration//GEN-END:variables
}
