/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;


/**
 *
 * @author gcoaquira
 */
public class FrmVerEstudiante extends javax.swing.JFrame {

    /**
     * Creates new form FrmVerEstudiante
     */
      int x, y;
    public FrmVerEstudiante() {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/imagenes/iconoCod.png")).getImage());
        this.setLocationRelativeTo(null);

        
        txtcodigoE.setText(pnlEstudiantes.VCodigo);
        txtdniE.setText(pnlEstudiantes.VDni);
        txtnombresE.setText(pnlEstudiantes.VNombre);
        txtapellidosE.setText(pnlEstudiantes.VApellidos);
        txtfacultadE.setText(pnlEstudiantes.VFacultad);
        txtescuelaE.setText(pnlEstudiantes.VEscuela);
        txtcodigoE.setText(pnlEstudiantes.VCodigo+"");
    }
     private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {                                     
        x = evt.getX();
        y = evt.getY();
    }    
     public void setEjecuar()
     {
         qr();
         
     }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel10 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtcodigoE = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        txtdniE = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtnombresE = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txtapellidosE = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txtfacultadE = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        txtescuelaE = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        codigo = new javax.swing.JLabel();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusTraversalPolicyProvider(true);
        setType(java.awt.Window.Type.UTILITY);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(10, 36, 95));
        jLabel1.setText("Código:");
        jPanel10.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, -1, 20));

        txtcodigoE.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtcodigoE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcodigoEKeyReleased(evt);
            }
        });
        jPanel10.add(txtcodigoE, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 260, 33));

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(10, 36, 95));
        jLabel35.setText("DNI:");
        jPanel10.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, -1, -1));

        txtdniE.setEditable(false);
        txtdniE.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel10.add(txtdniE, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, 260, 33));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(10, 36, 95));
        jLabel2.setText("Nombres:");
        jPanel10.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 70, 20));

        txtnombresE.setEditable(false);
        txtnombresE.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel10.add(txtnombresE, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 260, 33));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(10, 36, 95));
        jLabel27.setText("Apellidos:");
        jPanel10.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 70, 20));

        txtapellidosE.setEditable(false);
        txtapellidosE.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel10.add(txtapellidosE, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, 260, 33));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(10, 36, 95));
        jLabel25.setText("Facultad:");
        jPanel10.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, -1, 20));

        txtfacultadE.setEditable(false);
        txtfacultadE.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel10.add(txtfacultadE, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, 260, 33));

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(10, 36, 95));
        jLabel34.setText("Escuela:");
        jPanel10.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, -1, 20));

        txtescuelaE.setEditable(false);
        txtescuelaE.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel10.add(txtescuelaE, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, 260, 33));

        jPanel1.setBackground(new java.awt.Color(10, 36, 95));

        jLabel21.setFont(new java.awt.Font("Candara", 1, 30)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("UNIVERSIDAD PRIVADA DE TACNA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel21)
                .addContainerGap(156, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
        );

        jPanel10.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(242, 187, 10));

        jLabel36.setFont(new java.awt.Font("Candara", 1, 30)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(51, 51, 51));
        jLabel36.setText("CARNÉ DE BECARIO");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(207, Short.MAX_VALUE)
                .addComponent(jLabel36)
                .addGap(203, 203, 203))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel36)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel10.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, -1, 60));

        codigo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        codigo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel10.add(codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 260, 260));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
Color colorp = Color.white, colors = Color.black;
MyQRCreator qr = new MyQRCreator();
BufferedImage iconoSys = null;
    private void txtcodigoEKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcodigoEKeyReleased
    
        
        if (this.txtcodigoE.getText().length() > 0) {
            iconoSys = qr.createQR(this.txtcodigoE.getText(), 345, colorp, colors);
            ImageIcon QR = new ImageIcon(iconoSys);
            this.codigo.setIcon(QR);
            //            iconoSys = qr.createQR(this.texto.getText(), 500);
        } else {
            iconoSys = null;
            this.codigo.setIcon(null);
        }
    }//GEN-LAST:event_txtcodigoEKeyReleased

    public void qr()
    {
           if (this.txtcodigoE.getText().length() > 0) {
            iconoSys = qr.createQR(this.txtcodigoE.getText(), 345, colorp, colors);
            ImageIcon QR = new ImageIcon(iconoSys);
            this.codigo.setIcon(QR);
            //            iconoSys = qr.createQR(this.texto.getText(), 500);
        } else {
            iconoSys = null;
            this.codigo.setIcon(null);
        }
    }
       private void secundarioActionPerformed(java.awt.event.ActionEvent evt) {                                           
        if (iconoSys == null) {
            JOptionPane.showMessageDialog(this, "Debe generar un código QR\npara usar los colores.", "No genero código", 0,
                    new ImageIcon(getClass().getResource("/imagenes/msj_info.png")));
        } else {
            Color colorT = colors;
            JColorChooser ventanaDeColores = new JColorChooser();
            colors = ventanaDeColores.showDialog(this, "Seleccione un Color", Color.black);

            if (colors != null) {

                iconoSys = new BufferedImage(345, 345, BufferedImage.TYPE_INT_RGB);
                iconoSys.createGraphics();
                Graphics2D graphics = (Graphics2D) iconoSys.getGraphics();
                graphics.setColor(colorp);
                graphics.fillRect(0, 0, 345, 345);
                graphics.setColor(colors);

                for (int i = 0; i < 345; i++) {
                    for (int j = 0; j < 345; j++) {
                        if (MyQRCreator.matrix.get(i, j)) {
                            graphics.fillRect(i, j, 1, 1);
                        }
                    }
                }

                ImageIcon QR = new ImageIcon(iconoSys);
                this.codigo.setIcon(QR);
            } else {
                colors = colorT;
            }
        }
    } 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmVerEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmVerEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmVerEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmVerEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmVerEstudiante().setVisible(true);
            }
        });
    }
//     private org.edisoncor.gui.button.ButtonSeven secundario;
//  private org.edisoncor.gui.button.ButtonSeven primario;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbosexo;
    private javax.swing.JComboBox<String> cbosexo1;
    private javax.swing.JLabel codigo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField txtapellidos;
    private javax.swing.JTextField txtapellidos1;
    private javax.swing.JTextField txtapellidosE;
    private javax.swing.JTextField txtapellidosV;
    private javax.swing.JTextField txtapellidosV1;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtcodigo1;
    private javax.swing.JTextField txtcodigoE;
    private javax.swing.JTextField txtcodigoV;
    private javax.swing.JTextField txtcodigoV1;
    private javax.swing.JTextField txtcorreo;
    private javax.swing.JTextField txtcorreo1;
    private javax.swing.JTextField txtdireccion;
    private javax.swing.JTextField txtdireccion1;
    private javax.swing.JTextField txtdni;
    private javax.swing.JTextField txtdni1;
    private javax.swing.JTextField txtdniE;
    private javax.swing.JTextField txtdniV;
    private javax.swing.JTextField txtdniV1;
    private javax.swing.JTextField txtescuelaE;
    private javax.swing.JTextField txtfacultadE;
    private javax.swing.JTextField txtfechanacimiento;
    private javax.swing.JTextField txtfechanacimiento1;
    private javax.swing.JTextField txtnombres;
    private javax.swing.JTextField txtnombres1;
    private javax.swing.JTextField txtnombresE;
    private javax.swing.JTextField txtnombresV;
    private javax.swing.JTextField txtnombresV1;
    private javax.swing.JTextField txttelefono;
    private javax.swing.JTextField txttelefono1;
    // End of variables declaration//GEN-END:variables
}
