/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.DefaultComboBoxModel;
import principal.Principal;

import  Entidad.ClsEntUbicacion;
import Negocio.ClsNegUbicacion;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

import Entidad.ClsEntResponsable;
import Negocio.ClsNegResponsable;


import Entidad.ClsEntEvento;
import Negocio.ClsNegEvento;
import java.text.SimpleDateFormat;
import java.util.Date;

import Entidad.ClsEntEscuela;
import Entidad.ClsEntFacultad;
import Negocio.ClsNegEscuela;
import Negocio.ClsNegFacultdad;

import Entidad.ClsEntEstudiante;
import Negocio.ClsNegEstudiante;

import Entidad.ClsEntFacultadInvitada;
import Negocio.ClsNegFacultdadInvitada;

import Entidad.ClsEntInvitados;
import Negocio.ClsNegInvitados;

import javax.swing.table.DefaultTableModel;


/**
 *
 * @author gcoaquira
 */
public class pnlAgregarEvento extends javax.swing.JPanel {
    static   ResultSet rs=null;
     String codigo;
    int registro;
      int registro1;
     String titulo[]= {"Codigo","Facultdad","idescuela","Escuela"};        
        DefaultTableModel dtm4=new DefaultTableModel(null,titulo);
        
         String titulo5[]={"id_escu","codigo","Nombre","id_facu"};
          DefaultTableModel dtm5=new DefaultTableModel(null,titulo5);
    /**
     * Creates new form pnlAgregarEvento
     */
    public pnlAgregarEvento() {
        initComponents();        
        
        cargarcomUbicacion();
        cargarcomboResponsable();
        CargarComboFacultdad();
          txtfecha.setText(""+FEchaactual());
         // tblestudiantes.setVisible(false);
          txtcantidad.setVisible(false);
          
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txthorainicio = new javax.swing.JTextField();
        txtfecha = new javax.swing.JTextField();
        txthorafin = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtcodigo = new javax.swing.JTextField();
        txttitulo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cboestado = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtdescripcion = new javax.swing.JTextArea();
        btnGuardar = new rscomponentshade.RSButtonShade();
        btnCancelar = new rscomponentshade.RSButtonShade();
        jPanel6 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtreferencia = new javax.swing.JTextField();
        txtdireccion = new javax.swing.JTextField();
        cbolugar = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtcargo = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        cbodresponsable = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblinvitados = new javax.swing.JTable();
        cbo1 = new javax.swing.JComboBox<>();
        cbo2 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        txtcantidad = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblestudiantes = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2), "FORMULARIO DE NUEVO EVENTO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(51, 51, 51))); // NOI18N

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "FECHA Y HORA DEL EVENTO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(10, 36, 95));
        jLabel10.setText("Fecha:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(10, 36, 95));
        jLabel12.setText("Hora de Inicio:");

        txthorainicio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtfecha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txthorafin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(10, 36, 95));
        jLabel13.setText("Hora de Termino:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txthorainicio, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13))
                    .addComponent(txtfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txthorafin, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txthorainicio, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(txthorafin, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "DATOS  EVENTOS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(10, 36, 95));
        jLabel5.setText("Estado:");

        txtcodigo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txttitulo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(10, 36, 95));
        jLabel2.setText("Titulo:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(10, 36, 95));
        jLabel3.setText("Descripción:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(10, 36, 95));
        jLabel1.setText("Código:");

        cboestado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cboestado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));

        txtdescripcion.setColumns(20);
        txtdescripcion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtdescripcion.setForeground(new java.awt.Color(51, 51, 51));
        txtdescripcion.setRows(5);
        jScrollPane2.setViewportView(txtdescripcion);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(txttitulo))
                .addGap(339, 339, 339))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cboestado, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboestado, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        btnGuardar.setBackground(new java.awt.Color(6, 20, 51));
        btnGuardar.setText("Guardar");
        btnGuardar.setBgHover(new java.awt.Color(10, 36, 95));
        btnGuardar.setBgShade(new java.awt.Color(255, 255, 255));
        btnGuardar.setBgShadeHover(new java.awt.Color(242, 187, 10));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(6, 20, 51));
        btnCancelar.setText("Cancelar");
        btnCancelar.setBgHover(new java.awt.Color(10, 36, 95));
        btnCancelar.setBgShade(new java.awt.Color(255, 255, 255));
        btnCancelar.setBgShadeHover(new java.awt.Color(242, 187, 10));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "UBICACIÓN DEL EVENTO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(10, 36, 95));
        jLabel18.setText("Dirección:");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(10, 36, 95));
        jLabel19.setText("Referencia:");

        txtreferencia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtdireccion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        cbolugar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbolugar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-seleccione-" }));
        cbolugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbolugarActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(10, 36, 95));
        jLabel23.setText("Lugar");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel19)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel23)
                        .addComponent(jLabel18)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtdireccion)
                    .addComponent(txtreferencia)
                    .addComponent(cbolugar, 0, 398, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbolugar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtreferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "RESPONSABLE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(10, 36, 95));
        jLabel14.setText("Nombres y Apellidos:");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(10, 36, 95));
        jLabel20.setText("Cargo:");

        txtcargo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtnombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        cbodresponsable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbodresponsable.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-seleccione-" }));
        cbodresponsable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbodresponsableActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(10, 36, 95));
        jLabel21.setText("Bsuque");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel20))
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtcargo, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtnombre, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbodresponsable, 0, 349, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbodresponsable, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtcargo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tblinvitados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblinvitados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblinvitadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblinvitados);

        cbo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo1ActionPerformed(evt);
            }
        });

        cbo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo2ActionPerformed(evt);
            }
        });

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tblestudiantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(tblestudiantes);

        jButton2.setText("X");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(95, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(cbo1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbo2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton3))))
                        .addContainerGap(20, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addGap(20, 20, 20)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbo1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbo2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    
       int  intcontador;
       int idper[]=new int[100];
    void cargarcomUbicacion()
     {
         ClsNegUbicacion Ubicacion=new ClsNegUbicacion();
         ArrayList<ClsEntUbicacion> Ubi=Ubicacion.ListarUbicacion();
         Iterator iterator=Ubi.iterator();
         DefaultComboBoxModel modelo=new DefaultComboBoxModel();
         
         modelo.removeAllElements();
         
         String columna[]=new String[3];
          intcontador=0;
          while (iterator.hasNext())
          {
              ClsEntUbicacion Ubica=new ClsEntUbicacion();
              Ubica=(ClsEntUbicacion) iterator.next();              
              idper[intcontador]=Ubica.getId_ubi();
              columna[0]=Ubica.getLugar_ubi();
              columna[1]=Ubica.getDireccion_ubi();
                columna[2]=Ubica.getReferencia_ubi();
            
              
               modelo.addElement(Ubica.getLugar_ubi());
               intcontador ++;
          }
          cbolugar.setModel(modelo);
     }
    
       int  intcontador1;
       int idper1[]=new int[100];
     void cargarcomboResponsable()
     {

         ClsNegResponsable Responsable=new ClsNegResponsable();
         ArrayList<ClsEntResponsable> Ubi=Responsable.ListarResponsable();
         Iterator iterator=Ubi.iterator();
         DefaultComboBoxModel modelo1=new DefaultComboBoxModel();
         
         modelo1.removeAllElements();
         
         String columna[]=new String[3];
          intcontador1=0;
          while (iterator.hasNext())
          {
              ClsEntResponsable Respo=new ClsEntResponsable();
              Respo=(ClsEntResponsable) iterator.next();              
              idper1[intcontador1]=Respo.getId_respo();
              columna[0]=Respo.getNombre_respo();
              columna[1]=Respo.getApellido_respo();
                columna[2]= String.valueOf(Respo.getId_cargo());            
              
               modelo1.addElement(Respo.getId_respo());
               intcontador1 ++;
          }
          cbodresponsable.setModel(modelo1);
     }
     
     int  intcontador3;
       int idper3[]=new int[100];
     public void CargarComboFacultdad()

     {
          ClsNegFacultdad Facultdad=new ClsNegFacultdad();
         ArrayList<ClsEntUbicacion> Facu=Facultdad.ListarFacultdad();
         Iterator iterator=Facu.iterator();
         DefaultComboBoxModel modelo1=new DefaultComboBoxModel();
         
         modelo1.removeAllElements();
         
         String columna[]=new String[3];
          intcontador3=0;
          while (iterator.hasNext())
          {
              ClsEntFacultad FAcu=new ClsEntFacultad();
              FAcu=(ClsEntFacultad) iterator.next();              
              idper3[intcontador3]=FAcu.getId_facu();
              columna[0]=FAcu.getNombre_facu();          
            
               modelo1.addElement(FAcu.getNombre_facu());
               intcontador3 ++;
          }
          cbo1.setModel(modelo1);
     }
     public static  String FEchaactual()
              {
                    Date fecha = new Date();
                    SimpleDateFormat Formato =new SimpleDateFormat("dd/MM/YYYY");
                    return  Formato.format(fecha);
              }
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
       
        ClsEntEvento o = new ClsEntEvento();
        ClsNegEvento ob = new  ClsNegEvento();
        o.setId_eve(Integer.parseInt(txtcodigo.getText()));
        o.setTitulo_eve(txttitulo.getText());
        o.setDescripcion_eve(txtdescripcion.getText());
        o.setEstado_eve(cboestado.getSelectedItem().toString());
        o.setId_ubi(idper[cbolugar.getSelectedIndex()]);
        o.setFecha_eve(txtfecha.getText());
        o.setHorainicio_eve(txthorainicio.getText());
        o.setHorafin_eve(txthorafin.getText());
        o.setId_respo(idper1[cbodresponsable.getSelectedIndex()]);
        ob.AgregarEvento(o);
        JOptionPane.showMessageDialog(null,"Registrado po");
           
        GuardarTablaInvidatos();
         GuardarInividatos2();
         
         
        new CambiaPanel(Principal.pnlPrincipal, new paneles.pnlEventos());
        Principal.lblTitulo.setText("Registro de Nuevo Estudiante");
    }//GEN-LAST:event_btnGuardarActionPerformed

     public void GuardarTablaInvidatos()
    {
        for (int i = 0; i < tblinvitados.getRowCount(); i++) {
             ClsEntFacultadInvitada o  =  new ClsEntFacultadInvitada();     
            ClsNegFacultdadInvitada ob = new  ClsNegFacultdadInvitada();
            o.setId_eve(Integer.parseInt(txtcodigo.getText()));
           o.setId_facu(Integer.parseInt(tblinvitados.getValueAt(i,0).toString()));
           o.setNombre_facu(tblinvitados.getValueAt(i,1).toString());
           o.setId_escu(Integer.parseInt(tblinvitados.getValueAt(i,2).toString()));
           o.setNombre_escu(tblinvitados.getValueAt(i, 3).toString());
           
           ob.AgregarFacultadInvitada(o);          
            
        }
    
    }
     public void GuardarInividatos2()
     {
         for (int i = 0; i <tblestudiantes.getRowCount(); i++) {
             ClsEntInvitados o = new ClsEntInvitados();
             ClsNegInvitados ob = new ClsNegInvitados();
             o.setId_eve(Integer.parseInt(txtcodigo.getText()));
             o.setNombre_escu("me equivoque aqui :D");
             o.setId_escu(Integer.parseInt(tblestudiantes.getValueAt(i,0).toString()));
             o.setId_estu(Integer.parseInt(tblestudiantes.getValueAt(i,1).toString()));
            o.setNombre_estu(tblestudiantes.getValueAt(i,2).toString());
            o.setEstado("Aun No Asiste");
            o.setHoraE("");
            o.setHoraS("");
            o.setId_facu(Integer.parseInt(tblestudiantes.getValueAt(i,3).toString()));
            
            ob.AgregarInvitados(o);
            
           //  {"id_escu","codigo","Nombre",};
            
         }
     }            
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void cbolugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbolugarActionPerformed

        ClsNegUbicacion dispositivo = new ClsNegUbicacion();
        try{

            rs=dispositivo.ConsultarUbicacion(idper[cbolugar.getSelectedIndex()]);
            boolean encuentra =false;
            while(rs.next()){
                txtdireccion.setText((String) rs.getString(3));
                txtreferencia.setText((String) rs.getString(4));
                encuentra= true;
            }
            if(encuentra== false){
                JOptionPane.showMessageDialog(null,"No existen registros","Tabla Consultas",1);
            }

        }catch(Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_cbolugarActionPerformed
  int idcargo;
  
   
    private void cbodresponsableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbodresponsableActionPerformed
        // TODO add your handling code here:
        
      
        ClsNegResponsable Responsable = new ClsNegResponsable();
        try{

            rs=Responsable.ConsultarResponsable(idper1[cbodresponsable.getSelectedIndex()]);
            boolean encuentra =false;
            while(rs.next()){
                txtnombre.setText((String) rs.getString(2));
                idcargo=rs.getInt(4);
             //  JOptionPane.showMessageDialog(null,idcargo);
              //  txtcargo.setText((String) rs.getString(4));
                encuentra= true;
             //  probar();
             probar2();
            }
            if(encuentra== false){
                JOptionPane.showMessageDialog(null,"No existen registros","Tabla Consultas",1);
            }

        }catch(Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_cbodresponsableActionPerformed
       
       int  intcontador4;
       int idper4[]=new int[100];
    private void cbo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo1ActionPerformed
        // TODO add your handling code here:

        ClsNegEscuela consumos=new ClsNegEscuela();

        ArrayList<ClsEntEscuela> empleado=consumos.ListarPorEscuela(idper3[cbo1.getSelectedIndex()]);
        Iterator iterator=empleado.iterator();
        DefaultComboBoxModel modelo2=new DefaultComboBoxModel();

        String columna[]=new String[8];
        intcontador4=0;
        while (iterator.hasNext()) {
            ClsEntEscuela Escuelita=new ClsEntEscuela();
            Escuelita=(ClsEntEscuela) iterator.next();
            idper4[intcontador4]=Escuelita.getId_escu();
            columna[0]=String.valueOf(Escuelita.getId_escu());
            columna[1]=Escuelita.getIniciales_escu();
            columna[2]=Escuelita.getNombre_escu();

            modelo2.addElement(Escuelita.getNombre_escu());
            intcontador4++;
        }

        cbo2.setModel(modelo2);

        //          ClsNegFacultdad Facultdad=new ClsNegFacultdad();
        //         ArrayList<ClsEntUbicacion> Facu=Facultdad.ListarFacultdad();
        //         Iterator iterator=Facu.iterator();
        //         DefaultComboBoxModel modelo1=new DefaultComboBoxModel();
        //
        //         modelo1.removeAllElements();
        //
        //         String columna[]=new String[3];
        //          intcontador3=0;
        //          while (iterator.hasNext())
        //          {
            //              ClsEntFacultad FAcu=new ClsEntFacultad();
            //              FAcu=(ClsEntFacultad) iterator.next();
            //              idper3[intcontador3]=FAcu.getId_facu();
            //              columna[0]=FAcu.getNombre_facu();
            //
            //
            //               modelo1.addElement(FAcu.getNombre_facu());
            //               intcontador3 ++;
            //          }
        //          cbo1.setModel(modelo1);
        //

    }//GEN-LAST:event_cbo1ActionPerformed

    private void cbo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbo2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        ClsNegEscuela consumos=new ClsNegEscuela();
        
        ArrayList<ClsEntEscuela> Escuelas=consumos.ListarCantidadEstudiantesEnEscuela(idper4[cbo2.getSelectedIndex()]);
        Iterator iterator=Escuelas.iterator();
            
        while (iterator.hasNext()) {
            ClsEntEscuela Escuelita=new ClsEntEscuela();
            Escuelita=(ClsEntEscuela) iterator.next();
            txtcantidad.setText(""+Escuelita.getCantidad());          
        }
        int cantidad;
        cantidad=Integer.parseInt(txtcantidad.getText());
        
        if (cantidad==0) {
            JOptionPane.showMessageDialog(null,"No hay Estudiantes en esta Escuela");
            return;
        }
        else {
            String Escuela;
           Escuela = cbo2.getSelectedItem().toString();

           String  columna[]=new String[4];
           columna[0]=String.valueOf(idper3[cbo1.getSelectedIndex()]);
           columna[1]=cbo1.getSelectedItem().toString();
           columna[2]=String.valueOf(idper4[cbo2.getSelectedIndex()]);
           columna[3]=Escuela;
           dtm4.addRow(columna);

            for (int j = 0; j < columna.length; j++) {

                tblinvitados.setModel(dtm4);
            }             
        //LISTAR ESTUDIANTES SEGUN SU ID ESCUELA  PO
        
         
        ClsNegEstudiante estudi=new ClsNegEstudiante();     
        
        ArrayList<ClsEntEstudiante> EStu=estudi.ListarEstudiantesPorEscuela(idper4[cbo2.getSelectedIndex()]);
     
       //  JOptionPane.showMessageDialog(null,idper4[cbo2.getSelectedIndex()]);
        Iterator iterator1=EStu.iterator();
      
        
        String columna2[]=new String[4];
        while (iterator1.hasNext()) {
            ClsEntEstudiante ES=new ClsEntEstudiante();
            ES=(ClsEntEstudiante) iterator1.next();
            columna2[0]=String.valueOf(ES.getId_escu());               
             columna2[1]=String.valueOf(ES.getCodigo_estu());
            columna2[2]=ES.getNombre_estu(); 
              columna2[3]=String.valueOf(ES.getId_facu()); 
            
            // JOptionPane.showMessageDialog(null,ES.getNombre_estu());
          //  {"id_escu","codigo","Nombre",};
                dtm5.addRow(columna2);
            
        }     
        
         tblestudiantes.setModel(dtm5); 
        }
          

        //HACER DESPUE ESTO
        //        for (int i = 0; i < tblinvitados.getRowCount(); i++) {
            //            if (Escuela.equals(tblinvitados.getValueAt(i,2).toString())) {
                //                    JOptionPae.showMessageDialog(null,"ya esta esta escuela");
                //                }
            //
            //           }

    }//GEN-LAST:event_jButton1ActionPerformed
DefaultTableModel dtm6=new DefaultTableModel();
    void SeleccionarTabla(){        
        
        registro=tblinvitados.getSelectedRow();
        if (registro==-1) {
            JOptionPane.showMessageDialog(null, "Se debe seleccionar un registro...","Tabla Dispositivo",2);
        }
        else{
            dtm6=(DefaultTableModel) tblinvitados.getModel(); 
            codigo=((String)dtm6.getValueAt(registro, 2));
           
        }
    }
  //  String codigo2=0;
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        int rpta;
        rpta = JOptionPane.showConfirmDialog(null, "¿Estas seguro de eliminar este registro...?","Eliminar",0);

        if (rpta==0) {
           
            //usuario.EliminarUsuario(codigo);
            dtm6.removeRow(registro);
          //  JOptionPane.showMessageDialog(null,codigo);
            eliminarBusqueda(codigo);
            
            
        }
    }//GEN-LAST:event_jButton2ActionPerformed

     private boolean eliminarBusqueda(String codigo){
        for (int i = 0; i < tblestudiantes.getRowCount(); i++) {
            if (tblestudiantes.getValueAt(i,0).toString().equals(codigo)) {
              //  System.out.println(i);
                dtm5.removeRow(i);
                
                if(eliminarBusqueda(codigo)){
                    return true;
                }
            }
        }
        
        return false;
    }
    
    private void tblinvitadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblinvitadosMouseClicked
        // TODO add your handling code here:
        SeleccionarTabla();
    }//GEN-LAST:event_tblinvitadosMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
      
        
        
       // int numrows= tblestudiantes.getSelectedRow();
//       int[] selectRow=tblestudiantes.getSelectedRows();
//       int del=1;
//        for (int i = 0; i < selectRow.length; i++) {
//            dtm5.removeRow(selectRow[i]);
//            if (i<selectRow.length-1) {
//                selectRow[i+1]=selectRow[i+1]-del;
//                del=del+1;
//                
//                
//            }
//        }
    }//GEN-LAST:event_jButton3ActionPerformed

        int  intcontador2;
       int idper2[]=new int[100];      
       
       public void probar2()
       {
           ClsNegResponsable Resposable = new ClsNegResponsable();
        try{

            rs=Resposable.ConsultarResponsable2(idcargo);
            boolean encuentra =false;
            while(rs.next()){
                
                txtcargo.setText((String) rs.getString(2));
                encuentra= true;
            }
            if(encuentra== false){
                JOptionPane.showMessageDialog(null,"No existen registros","Tabla Consultas",1);
            }

        }catch(Exception ex){
            ex.printStackTrace();
        }
       }
    public void probar()

    {//ESTO NO FUNCIONA
        
    
//       int idper1[]=new int[100];
         ClsNegResponsable Responsable=new ClsNegResponsable();
         ArrayList<ClsEntResponsable> Ubi=Responsable.ListarResponsable2(idcargo);
         Iterator iterator=Ubi.iterator();
         //DefaultComboBoxModel modelo1=new DefaultComboBoxModel();
         
       //  modelo1.removeAllElements();
         
         String columna[]=new String[3];
          intcontador2=0;
          while (iterator.hasNext())
          {
              ClsEntResponsable Respo=new ClsEntResponsable();
              Respo=(ClsEntResponsable) iterator.next();              
              idper2[intcontador2]=Respo.getId_respo();
              columna[0]=Respo.getNombre_respo();
        
                columna[1]= String.valueOf(Respo.getId_cargo());
                  columna[2]= String.valueOf(Respo.getCargo());
       
               intcontador2 ++;
               txtcargo.setText(String.valueOf(Respo.getCargo()));
          }
          
          
        //  cbodresponsable.setModel(modelo1);
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rscomponentshade.RSButtonShade btnCancelar;
    private rscomponentshade.RSButtonShade btnGuardar;
    private javax.swing.JComboBox<String> cbo1;
    private javax.swing.JComboBox<String> cbo2;
    private javax.swing.JComboBox<String> cbodresponsable;
    private javax.swing.JComboBox<String> cboestado;
    private javax.swing.JComboBox<String> cbolugar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblestudiantes;
    private javax.swing.JTable tblinvitados;
    private javax.swing.JTextField txtcantidad;
    private javax.swing.JTextField txtcargo;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextArea txtdescripcion;
    private javax.swing.JTextField txtdireccion;
    private javax.swing.JTextField txtfecha;
    private javax.swing.JTextField txthorafin;
    private javax.swing.JTextField txthorainicio;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtreferencia;
    private javax.swing.JTextField txttitulo;
    // End of variables declaration//GEN-END:variables
}
