/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import javax.swing.JOptionPane;

import Entidad.ClsEntComunicados;
import Negocio.ClsNegComunicados;

import Entidad.ClsEntEstudiante;
import Entidad.ClsEntEvento;
import Negocio.ClsNegEstudiante;
import Negocio.ClsNegEvento;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import static java.util.Locale.filter;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.ListSelectionModel;
import javax.swing.RowFilter;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author gcoaquira
 */
public class pnlComunicados extends javax.swing.JPanel {
    
 private FileNameExtensionFilter filter=new FileNameExtensionFilter("Archuvos pdf y word","pdf","docx");
 String titulo[]={"Codigo","Dni","Nombre","Apellido","Telefono","Eamil"};
 DefaultTableModel dtm=new DefaultTableModel(null,titulo);
 
    /**
     * Creates new form pnlComunicados
     */
    public pnlComunicados() {
        initComponents();
         cargarcomEventos();
        txtfecha.setVisible(false);
       txtfecha.setText(""+FEchaactual());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblEstudiantes = new javax.swing.JTable(){
            /*
            public Class getColumnClass(int col){
                return col == 0 ? Boolean.class:Object.class;
            }
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return columnIndex == 0;
            }
            */
        };
        txtFiltro = new rscomponentshade.RSTextFieldShade();
        cboeventos = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        btnGuardar = new rscomponentshade.RSButtonShade();
        txtIdCliente = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtasunto = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtDestino = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtmensaje = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtnombrearchivo = new javax.swing.JTextField();
        txtruta2 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        btnAdjuntarArchivo = new rscomponentshade.RSButtonShade();
        btnSeleccionarTodos = new javax.swing.JButton();
        txtfecha = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtFiltro2 = new rscomponentshade.RSTextFieldShade();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblComunicados = new javax.swing.JTable();

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2), "FORMULARIO DE COMUNICADOS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(51, 51, 51))); // NOI18N

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "LISTA ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        tblEstudiantes.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tblEstudiantes.setForeground(new java.awt.Color(52, 73, 94));
        tblEstudiantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblEstudiantes.setGridColor(new java.awt.Color(204, 204, 204));
        jScrollPane3.setViewportView(tblEstudiantes);

        txtFiltro.setPlaceholder("Filtrar datos");
        txtFiltro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFiltroKeyTyped(evt);
            }
        });

        cboeventos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboeventos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboeventosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cboeventos, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboeventos, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "DETALLE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        btnGuardar.setBackground(new java.awt.Color(6, 20, 51));
        btnGuardar.setText("Enviar");
        btnGuardar.setBgHover(new java.awt.Color(10, 36, 95));
        btnGuardar.setBgShade(new java.awt.Color(255, 255, 255));
        btnGuardar.setBgShadeHover(new java.awt.Color(242, 187, 10));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        txtIdCliente.setEditable(false);
        txtIdCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtIdCliente.setForeground(new java.awt.Color(51, 51, 51));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(10, 36, 95));
        jLabel12.setText("Id Cliente:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(10, 36, 95));
        jLabel9.setText("Asunto:");

        txtasunto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtasunto.setForeground(new java.awt.Color(51, 51, 51));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(10, 36, 95));
        jLabel10.setText("Correo:");

        txtDestino.setEditable(false);
        txtDestino.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDestino.setForeground(new java.awt.Color(51, 51, 51));

        txtmensaje.setColumns(20);
        txtmensaje.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtmensaje.setForeground(new java.awt.Color(51, 51, 51));
        txtmensaje.setRows(5);
        jScrollPane2.setViewportView(txtmensaje);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(10, 36, 95));
        jLabel13.setText("Mensaje:");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(10, 36, 95));
        jLabel15.setText("Archivo:");

        txtnombrearchivo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtnombrearchivo.setForeground(new java.awt.Color(51, 51, 51));

        txtruta2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtruta2.setForeground(new java.awt.Color(51, 51, 51));
        txtruta2.setEnabled(false);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(10, 36, 95));
        jLabel14.setText("Ruta Archivo:");

        btnAdjuntarArchivo.setBackground(new java.awt.Color(52, 73, 94));
        btnAdjuntarArchivo.setBorder(null);
        btnAdjuntarArchivo.setBgHover(new java.awt.Color(41, 128, 185));
        btnAdjuntarArchivo.setBgShade(new java.awt.Color(204, 204, 204));
        btnAdjuntarArchivo.setBgShadeHover(new java.awt.Color(204, 204, 204));
        btnAdjuntarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdjuntarArchivoActionPerformed(evt);
            }
        });

        btnSeleccionarTodos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSeleccionarTodos.setText("Seleccionar Todo");
        btnSeleccionarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarTodosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(33, 33, 33)
                            .addComponent(jLabel12)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(50, 50, 50)
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtasunto, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(52, 52, 52)
                            .addComponent(jLabel10)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(43, 43, 43)
                            .addComponent(jLabel13)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnSeleccionarTodos))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(txtfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAdjuntarArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(37, 37, 37)
                                    .addComponent(jLabel15)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtnombrearchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel14)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtruta2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtasunto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnombrearchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtruta2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAdjuntarArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(btnSeleccionarTodos, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "LISTA ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(10, 36, 95));
        jLabel3.setText("Registro Comunicados");

        txtFiltro2.setPlaceholder("Filtrar datos");

        tblComunicados.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tblComunicados.setForeground(new java.awt.Color(52, 73, 94));
        tblComunicados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblComunicados.setGridColor(new java.awt.Color(204, 204, 204));
        tblComunicados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblComunicadosMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblComunicados);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(txtFiltro2, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(11, 11, 11)
                    .addComponent(jScrollPane5)
                    .addGap(12, 12, 12)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFiltro2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(0, 189, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                    .addContainerGap(51, Short.MAX_VALUE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(121, 121, 121))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 567, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
            enviarCorreo();


     

          for(String id_cliente:txtIdCliente.getText().split(",")){
               ClsEntComunicados o = new ClsEntComunicados();
                ClsNegComunicados ob =  new ClsNegComunicados();
            o.setId_eve(idper[cboeventos.getSelectedIndex()]);
            o.setCodig_estu(Integer.parseInt(id_cliente));
            o.setAsunComu(txtasunto.getText());
            o.setMensComu(txtmensaje.getText());
           
            o.setFechComu("23-05-2018");            
            ob.AgregarComunicado(o); 
        }
        
        ListarComunicados();      
        
    }//GEN-LAST:event_btnGuardarActionPerformed
public void  enviarCorreo(){
        
        ClsEntComunicados corre = new ClsEntComunicados();
        corre.setPassword("47199491++-");
        corre.setUsuario("guimerupt@gmail.com");
        corre.setAsunComu(txtasunto.getText());
        corre.setMensComu(txtmensaje.getText());
        corre.setDestino(txtDestino.getText().trim());
        corre.setArchComu(txtnombrearchivo.getText());
        corre.setRutaArchivo(txtruta2.getText());
        
        ClsNegComunicados c = new ClsNegComunicados();
        if(c.EnviarCorreos(corre)){
            JOptionPane.showMessageDialog(null,"envio con exito");
        }
        else{
              JOptionPane.showMessageDialog(null,"error");
        }
    
    }

    
     public void  ListarComunicados()
    {
              
         String titulo[]={"codigo","Asunto","Fecha"};
   DefaultTableModel dtm1=new DefaultTableModel(null,titulo);
       ClsNegComunicados Estudiante=new ClsNegComunicados();
        ArrayList<ClsEntComunicados> Escu=Estudiante.ListarComunicado();
        Iterator iterator=Escu.iterator();      
        
        String columna[]=new String[4];
        while (iterator.hasNext()) {
            ClsEntComunicados Estu=new ClsEntComunicados();
            Estu=(ClsEntComunicados) iterator.next();
            columna[0]=String.valueOf(Estu.getCodig_estu());
            columna[1]=Estu.getAsunComu();
            columna[2]=Estu.getFechComu();                                 
            dtm1.addRow(columna);
        }
        tblComunicados.setModel(dtm1);        

    }
    
     int  intcontador;
       int idper[]=new int[100];
    void cargarcomEventos()
     {
         ClsNegEvento Evento=new ClsNegEvento();
         ArrayList<ClsEntEvento> Eve=Evento.ListarEvento();
         Iterator iterator=Eve.iterator();
         DefaultComboBoxModel modelo=new DefaultComboBoxModel();
         
         modelo.removeAllElements();
         
         String columna[]=new String[3];
          intcontador=0;
          while (iterator.hasNext())
          {
              ClsEntEvento Even=new ClsEntEvento();
              Even=(ClsEntEvento) iterator.next();              
              idper[intcontador]=Even.getId_eve();
              columna[0]=String.valueOf(Even.getId_eve());
              columna[1]=Even.getTitulo_eve();              
               modelo.addElement(Even.getTitulo_eve());
               intcontador ++;
          }
          cboeventos.setModel(modelo);
     }
    
       String codigo;
   void SeleccionarTablaClientes(){    
       try 
       {
            StringBuffer sbIDs = new StringBuffer();
        StringBuffer sbDestinos = new StringBuffer();
        for(int i:tblEstudiantes.getSelectedRows()){
            sbIDs.append(tblEstudiantes.getValueAt(i, 0).toString());
            sbIDs.append(",");

            sbDestinos.append(tblEstudiantes.getValueAt(i, 3).toString());
            sbDestinos.append(",");
        }

        sbIDs.delete(sbIDs.length() -1,sbIDs.length());
        sbDestinos.delete(sbDestinos.length() -1,sbDestinos.length());

        codigo = sbIDs.toString();
        txtIdCliente.setText(sbIDs.toString());
        txtDestino.setText(sbDestinos.toString());
       }catch (Exception ex) {
            JOptionPane.showMessageDialog(null,"Error","prueba", 2);
            
        }
      
    }
   
   public void buscar1adsa()
    {
        String titulo1[]={"codigo","nombre","apellido","correo","Escuela"};

        ClsNegEstudiante consumos1=new ClsNegEstudiante();

        ArrayList<ClsEntEstudiante> empleado1=consumos1.ListarIvitadosAEvento(idper[cboeventos.getSelectedIndex()]);
    //    JOptionPane.showMessageDialog(null,idper[cboeventos.getSelectedIndex()]);
        Iterator iterator1=empleado1.iterator();
        DefaultTableModel dtm1=new DefaultTableModel(null,titulo1);

        String columna1[]=new String[5];
        while (iterator1.hasNext()) {
            ClsEntEstudiante Asis=new ClsEntEstudiante();
            Asis=(ClsEntEstudiante) iterator1.next();
            columna1[0]=String.valueOf(Asis.getCodigo_estu());
            columna1[1]=Asis.getNombre_estu();
            columna1[2]=Asis.getApellidos_estu();
            columna1[3]=Asis.getEmail_estu();
             columna1[4]= Asis.getNombre_escu();
                    

            dtm1.addRow(columna1);
        }

        tblEstudiantes.setModel(dtm1);
        
        tblEstudiantes.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        tblEstudiantes.setRowSelectionAllowed(true);
        tblEstudiantes.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent lse) {
                if (!lse.getValueIsAdjusting()) {
                    SeleccionarTablaClientes();
                }
            }
        });
    }
    
   
     public static  String FEchaactual()
              {
                    Date fecha = new Date();
                    SimpleDateFormat Formato =new SimpleDateFormat("dd/MM/YYYY");
                    return  Formato.format(fecha);
              }
    private void btnSeleccionarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarTodosActionPerformed
        tblEstudiantes.setRowSelectionInterval(0, tblEstudiantes.getRowCount() - 1);
        SeleccionarTablaClientes();
    }//GEN-LAST:event_btnSeleccionarTodosActionPerformed

    private void tblComunicadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblComunicadosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblComunicadosMouseClicked

    private void btnAdjuntarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdjuntarArchivoActionPerformed
         JFileChooser filechoose = new JFileChooser();
            filechoose.setFileFilter(filter);
        int opcion = filechoose.showOpenDialog(this);
        if (opcion==JFileChooser.APPROVE_OPTION) {
           String nomnre_archivo=filechoose.getSelectedFile().getName();
           String ruta=filechoose.getSelectedFile().getPath();
           txtnombrearchivo.setText(nomnre_archivo);
           txtruta2.setText(ruta);
        }
    }//GEN-LAST:event_btnAdjuntarArchivoActionPerformed
  TableRowSorter trs;
    public String leerBusqueda(){
        String busca=txtFiltro.getText().trim().replace("", "");
        return busca;
    }
    private void txtFiltroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFiltroKeyTyped
        // TODO add your handling code here:
        
        txtFiltro.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent ke) {
                trs.setRowFilter(RowFilter.regexFilter("(?i)"+leerBusqueda(), 0,1,2,3,4,5,6)); //Filtra datos
            }
        });
        trs=new TableRowSorter(dtm);
        tblEstudiantes.setRowSorter(trs);
    }//GEN-LAST:event_txtFiltroKeyTyped

    private void cboeventosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboeventosActionPerformed
        // TODO add your handling code here:
        buscar1adsa();
    }//GEN-LAST:event_cboeventosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rscomponentshade.RSButtonShade btnAdjuntarArchivo;
    private rscomponentshade.RSButtonShade btnGuardar;
    private javax.swing.JButton btnSeleccionarTodos;
    private javax.swing.JComboBox<String> cboeventos;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable tblComunicados;
    private javax.swing.JTable tblEstudiantes;
    private javax.swing.JTextField txtDestino;
    private rscomponentshade.RSTextFieldShade txtFiltro;
    private rscomponentshade.RSTextFieldShade txtFiltro2;
    private javax.swing.JTextField txtIdCliente;
    private javax.swing.JTextField txtasunto;
    private javax.swing.JTextField txtfecha;
    private javax.swing.JTextArea txtmensaje;
    private javax.swing.JTextField txtnombrearchivo;
    private javax.swing.JTextField txtruta2;
    // End of variables declaration//GEN-END:variables
}
