/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import Entidad.ClsEntEscuela;
import Negocio.ClsNegEscuela;
import java.awt.image.BufferedImage;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

import Entidad.ClsDatos;

/**
 *
 * @author usuario
 */
public class pnlConsultaEscuela extends javax.swing.JPanel {

    //public static  ArrayList <ClsDatos> Datoss=new ArrayList<ClsDatos>();
    /**
     * Creates new form pnlConsultaEscuela
     */
    public pnlConsultaEscuela() {
        initComponents();
         ListarEscuela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelcontenido = new javax.swing.JPanel();
        lblgrafico = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFacultad = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        panelcontenido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout panelcontenidoLayout = new javax.swing.GroupLayout(panelcontenido);
        panelcontenido.setLayout(panelcontenidoLayout);
        panelcontenidoLayout.setHorizontalGroup(
            panelcontenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelcontenidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblgrafico, javax.swing.GroupLayout.DEFAULT_SIZE, 738, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelcontenidoLayout.setVerticalGroup(
            panelcontenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelcontenidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblgrafico, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tblFacultad.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblFacultad);

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(panelcontenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addComponent(jButton2)
                .addGap(136, 136, 136))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(panelcontenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void  ListarEscuela()

    {
         String titulo[]={"IdEscuela","Iniciales","Cantidad"};
         
      
        ClsNegEscuela Escuela=new ClsNegEscuela();
        ArrayList<ClsEntEscuela> Escu=Escuela.ListarEscuela2();
        Iterator iterator=Escu.iterator();
        DefaultTableModel dtm=new DefaultTableModel(null,titulo);
        
        String columna[]=new String[5];
       while (iterator.hasNext()) {
            ClsEntEscuela Escuelita=new ClsEntEscuela();
            Escuelita=(ClsEntEscuela) iterator.next();
            columna[0]=String.valueOf(Escuelita.getId_escu());
            columna[1]=Escuelita.getIniciales_escu();
            columna[2]=String.valueOf(Escuelita.getCantidad());
     
            dtm.addRow(columna);
        }
        tblFacultad.setModel(dtm);   
        
        
        
//          for (int i = 0; i < tblFacultad.getRowCount(); i++) {
//            ClsDatos o = new  ClsDatos();
//            o.facultad=tblFacultad.getValueAt(i, 0).toString();
//            o.cantidad=Integer.parseInt(tblFacultad.getValueAt(i, 1).toString());
//            Datoss.add(o);
            
       // }
        
    }
     int cantidadfilas=0;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        cantidadfilas=tblFacultad.getRowCount();
        if (cantidadfilas==2) {
            grafico1();
        }
        if (cantidadfilas==3) {
            grafico2();
        }
        if (cantidadfilas==4) {
            grafico3();
        }
        if (cantidadfilas==5) {
            grafico4();
        }
        if (cantidadfilas==6) {
           grafico5();
        }
        if (cantidadfilas==7) {
            grafico6();
        }
        if (cantidadfilas==8) {
            grafico7();
        }
        if (cantidadfilas==9) {
            grafico8();
        }
        if (cantidadfilas==10) {
            grafico9();
        }
        if (cantidadfilas==11) {
            grafico10();
        }
        if (cantidadfilas==12) {
            grafico11();
        }
        
        if (cantidadfilas==13) {
            grafico12();
        }
        
        if (cantidadfilas==14) {
            grafico13();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
//        for (int i = 0; i <Datoss.size(); i++) {
//             JFreeChart barra=null;
//        DefaultCategoryDataset datos;
//        
//        datos = new DefaultCategoryDataset();
//
//      //  datos.setValue(Datoss.get(i).getFacultad(),String.valueOf(Datoss.get(i).getCantidad()),"");
//       // datos.setValue(facultdad2,tblFacultad.getValueAt(1,0).toString(),"");
//        }
        
    }//GEN-LAST:event_jButton2ActionPerformed
public void grafico1()
    {
        
     int facultad1=0,facultdad2=0,facultda3;

         facultad1=Integer.parseInt(tblFacultad.getValueAt(0,2).toString());
           facultdad2=Integer.parseInt(tblFacultad.getValueAt(1,2).toString());
        
        JFreeChart barra=null;
        DefaultCategoryDataset datos;
        
        datos = new DefaultCategoryDataset();

        datos.setValue(facultad1,tblFacultad.getValueAt(0,0).toString(),"");
        datos.setValue(facultdad2,tblFacultad.getValueAt(1,0).toString(),"");
       // datos.setValue(5,"electronica","");
       
        barra =ChartFactory.createBarChart3D("grafico de mas asistentes","EStudiantes","Cantidad",datos,PlotOrientation.VERTICAL,true,true,true);
       
        BufferedImage grafico= barra.createBufferedImage(panelcontenido.getWidth(),panelcontenido.getHeight());
        lblgrafico.setSize(panelcontenido.getSize());
        lblgrafico.setIcon(new ImageIcon(grafico));
        panelcontenido.updateUI();
        
        
      
    }

public void grafico2()
    {
        
     int facultad1=0,facultdad2=0,facultda3=0;
     
//        
//        
//        for (int i = 0; i < tblFacultad.getRowCount();i++) {
//            facultad1=Integer.parseInt(tblFacultad.getValueAt(i,3).toString());
//        }
         facultad1=Integer.parseInt(tblFacultad.getValueAt(0,2).toString());
           facultdad2=Integer.parseInt(tblFacultad.getValueAt(1,2).toString());
           facultda3=Integer.parseInt(tblFacultad.getValueAt(2,2).toString());
        
        JFreeChart barra=null;
        DefaultCategoryDataset datos;
        
        datos = new DefaultCategoryDataset();

        datos.setValue(facultad1,tblFacultad.getValueAt(0,0).toString(),"");
        datos.setValue(facultdad2,tblFacultad.getValueAt(1,0).toString(),"");
          datos.setValue(facultda3,tblFacultad.getValueAt(2,0).toString(),"");
          
       // datos.setValue(5,"electronica","");
       
        barra =ChartFactory.createBarChart3D("grafico de mas asistentes","EStudiantes","Cantidad",datos,PlotOrientation.VERTICAL,true,true,true);
       
        BufferedImage grafico= barra.createBufferedImage(panelcontenido.getWidth(),panelcontenido.getHeight());
        lblgrafico.setSize(panelcontenido.getSize());
        lblgrafico.setIcon(new ImageIcon(grafico));
        panelcontenido.updateUI();
    }
 public void grafico3()
    {
        
     int facultad1=0,facultdad2=0,facultda3=0,Facultda4=0;;
     
//        
//        
//        for (int i = 0; i < tblFacultad.getRowCount();i++) {
//            facultad1=Integer.parseInt(tblFacultad.getValueAt(i,3).toString());
//        }
         facultad1=Integer.parseInt(tblFacultad.getValueAt(0,2).toString());
           facultdad2=Integer.parseInt(tblFacultad.getValueAt(1,2).toString());
           facultda3=Integer.parseInt(tblFacultad.getValueAt(2,2).toString());
            Facultda4=Integer.parseInt(tblFacultad.getValueAt(3,2).toString());
        
        JFreeChart barra=null;
        DefaultCategoryDataset datos;
        
        datos = new DefaultCategoryDataset();

        datos.setValue(facultad1,tblFacultad.getValueAt(0,0).toString(),"");
        datos.setValue(facultdad2,tblFacultad.getValueAt(1,0).toString(),"");
          datos.setValue(facultda3,tblFacultad.getValueAt(2,0).toString(),"");
          datos.setValue(Facultda4,tblFacultad.getValueAt(3,0).toString(),"");
          
       // datos.setValue(5,"electronica","");
       
        barra =ChartFactory.createBarChart3D("grafico de mas asistentes","EStudiantes","Cantidad",datos,PlotOrientation.VERTICAL,true,true,true);
       
        BufferedImage grafico= barra.createBufferedImage(panelcontenido.getWidth(),panelcontenido.getHeight());
        lblgrafico.setSize(panelcontenido.getSize());
        lblgrafico.setIcon(new ImageIcon(grafico));
        panelcontenido.updateUI();
    }
 
  public void grafico4()
    {
        
     int facultad1=0,facultdad2=0,facultda3=0,Facultda4=0,Facultad5=0;
     
//        
//        
//        for (int i = 0; i < tblFacultad.getRowCount();i++) {
//            facultad1=Integer.parseInt(tblFacultad.getValueAt(i,3).toString());
//        }
         facultad1=Integer.parseInt(tblFacultad.getValueAt(0,2).toString());
           facultdad2=Integer.parseInt(tblFacultad.getValueAt(1,2).toString());
           facultda3=Integer.parseInt(tblFacultad.getValueAt(2,2).toString());
            Facultda4=Integer.parseInt(tblFacultad.getValueAt(3,2).toString());
            Facultad5=Integer.parseInt(tblFacultad.getValueAt(4,2).toString());
        
        JFreeChart barra=null;
        DefaultCategoryDataset datos;
        
        datos = new DefaultCategoryDataset();

        datos.setValue(facultad1,tblFacultad.getValueAt(0,0).toString(),"");
        datos.setValue(facultdad2,tblFacultad.getValueAt(1,0).toString(),"");
          datos.setValue(facultda3,tblFacultad.getValueAt(2,0).toString(),"");
          datos.setValue(Facultda4,tblFacultad.getValueAt(3,0).toString(),"");
          datos.setValue(Facultad5,tblFacultad.getValueAt(4,0).toString(),"");
          
       // datos.setValue(5,"electronica","");
       
        barra =ChartFactory.createBarChart3D("grafico de mas asistentes","EStudiantes","Cantidad",datos,PlotOrientation.VERTICAL,true,true,true);
       
        BufferedImage grafico= barra.createBufferedImage(panelcontenido.getWidth(),panelcontenido.getHeight());
        lblgrafico.setSize(panelcontenido.getSize());
        lblgrafico.setIcon(new ImageIcon(grafico));
        panelcontenido.updateUI();
    }
    public void grafico5()
    {
        
     int facultad1=0,facultdad2=0,facultda3=0,Facultda4=0,Facultad5=0,facultad6=0,facultad7=0;
     
//        
//        
//        for (int i = 0; i < tblFacultad.getRowCount();i++) {
//            facultad1=Integer.parseInt(tblFacultad.getValueAt(i,3).toString());
//        }
         facultad1=Integer.parseInt(tblFacultad.getValueAt(0,2).toString());
           facultdad2=Integer.parseInt(tblFacultad.getValueAt(1,2).toString());
           facultda3=Integer.parseInt(tblFacultad.getValueAt(2,2).toString());
            Facultda4=Integer.parseInt(tblFacultad.getValueAt(3,2).toString());
            Facultad5=Integer.parseInt(tblFacultad.getValueAt(4,2).toString());
             facultad6=Integer.parseInt(tblFacultad.getValueAt(5,2).toString());
               facultad7=Integer.parseInt(tblFacultad.getValueAt(6,2).toString());
        
        JFreeChart barra=null;
        DefaultCategoryDataset datos;
        
        datos = new DefaultCategoryDataset();

        datos.setValue(facultad1,tblFacultad.getValueAt(0,0).toString(),"");
        datos.setValue(facultdad2,tblFacultad.getValueAt(1,0).toString(),"");
          datos.setValue(facultda3,tblFacultad.getValueAt(2,0).toString(),"");
          datos.setValue(Facultda4,tblFacultad.getValueAt(3,0).toString(),"");
          datos.setValue(Facultad5,tblFacultad.getValueAt(4,0).toString(),"");
          datos.setValue(facultad6,tblFacultad.getValueAt(5,0).toString(),"");
            datos.setValue(facultad7,tblFacultad.getValueAt(6,0).toString(),"");
          
       // datos.setValue(5,"electronica","");
       
        barra =ChartFactory.createBarChart3D("grafico de mas asistentes","EStudiantes","Cantidad",datos,PlotOrientation.VERTICAL,true,true,true);
       
        BufferedImage grafico= barra.createBufferedImage(panelcontenido.getWidth(),panelcontenido.getHeight());
        lblgrafico.setSize(panelcontenido.getSize());
        lblgrafico.setIcon(new ImageIcon(grafico));
        panelcontenido.updateUI();
    }
        public void grafico6()
    {
        
     int facultad1=0,facultdad2=0,facultda3=0,Facultda4=0,Facultad5=0,facultad6=0;
     
//        
//        
//        for (int i = 0; i < tblFacultad.getRowCount();i++) {
//            facultad1=Integer.parseInt(tblFacultad.getValueAt(i,3).toString());
//        }
         facultad1=Integer.parseInt(tblFacultad.getValueAt(0,2).toString());
           facultdad2=Integer.parseInt(tblFacultad.getValueAt(1,2).toString());
           facultda3=Integer.parseInt(tblFacultad.getValueAt(2,2).toString());
            Facultda4=Integer.parseInt(tblFacultad.getValueAt(3,2).toString());
            Facultad5=Integer.parseInt(tblFacultad.getValueAt(4,2).toString());
             facultad6=Integer.parseInt(tblFacultad.getValueAt(5,2).toString());
        
        JFreeChart barra=null;
        DefaultCategoryDataset datos;
        
        datos = new DefaultCategoryDataset();

        datos.setValue(facultad1,tblFacultad.getValueAt(0,0).toString(),"");
        datos.setValue(facultdad2,tblFacultad.getValueAt(1,0).toString(),"");
          datos.setValue(facultda3,tblFacultad.getValueAt(2,0).toString(),"");
          datos.setValue(Facultda4,tblFacultad.getValueAt(3,0).toString(),"");
          datos.setValue(Facultad5,tblFacultad.getValueAt(4,0).toString(),"");
          datos.setValue(facultad6,tblFacultad.getValueAt(5,0).toString(),"");
          
       // datos.setValue(5,"electronica","");
       
        barra =ChartFactory.createBarChart3D("grafico de mas asistentes","EStudiantes","Cantidad",datos,PlotOrientation.VERTICAL,true,true,true);
       
        BufferedImage grafico= barra.createBufferedImage(panelcontenido.getWidth(),panelcontenido.getHeight());
        lblgrafico.setSize(panelcontenido.getSize());
        lblgrafico.setIcon(new ImageIcon(grafico));
        panelcontenido.updateUI();
    }
        
    public void grafico7()
    {
        
     int facultad1=0,facultdad2=0,facultda3=0,Facultda4=0,Facultad5=0,facultad6=0,facultad7;
     
//        
//        
//        for (int i = 0; i < tblFacultad.getRowCount();i++) {
//            facultad1=Integer.parseInt(tblFacultad.getValueAt(i,3).toString());
//        }
         facultad1=Integer.parseInt(tblFacultad.getValueAt(0,2).toString());
           facultdad2=Integer.parseInt(tblFacultad.getValueAt(1,2).toString());
           facultda3=Integer.parseInt(tblFacultad.getValueAt(2,2).toString());
            Facultda4=Integer.parseInt(tblFacultad.getValueAt(3,2).toString());
            Facultad5=Integer.parseInt(tblFacultad.getValueAt(4,2).toString());
             facultad6=Integer.parseInt(tblFacultad.getValueAt(5,2).toString());
             facultad7=Integer.parseInt(tblFacultad.getValueAt(6,2).toString());
        
        JFreeChart barra=null;
        DefaultCategoryDataset datos;
        
        datos = new DefaultCategoryDataset();

        datos.setValue(facultad1,tblFacultad.getValueAt(0,0).toString(),"");
        datos.setValue(facultdad2,tblFacultad.getValueAt(1,0).toString(),"");
          datos.setValue(facultda3,tblFacultad.getValueAt(2,0).toString(),"");
          datos.setValue(Facultda4,tblFacultad.getValueAt(3,0).toString(),"");
          datos.setValue(Facultad5,tblFacultad.getValueAt(4,0).toString(),"");
          datos.setValue(facultad6,tblFacultad.getValueAt(5,0).toString(),"");
            datos.setValue(facultad7,tblFacultad.getValueAt(6,0).toString(),"");
          
       // datos.setValue(5,"electronica","");
       
        barra =ChartFactory.createBarChart3D("grafico de mas asistentes","EStudiantes","Cantidad",datos,PlotOrientation.VERTICAL,true,true,true);
       
        BufferedImage grafico= barra.createBufferedImage(panelcontenido.getWidth(),panelcontenido.getHeight());
        lblgrafico.setSize(panelcontenido.getSize());
        lblgrafico.setIcon(new ImageIcon(grafico));
        panelcontenido.updateUI();
    }
       public void grafico8()
    {
        
     int facultad1=0,facultdad2=0,facultda3=0,Facultda4=0,Facultad5=0,facultad6=0,facultad7,facultad8;
     
//        
//        
//        for (int i = 0; i < tblFacultad.getRowCount();i++) {
//            facultad1=Integer.parseInt(tblFacultad.getValueAt(i,3).toString());
//        }
         facultad1=Integer.parseInt(tblFacultad.getValueAt(0,2).toString());
           facultdad2=Integer.parseInt(tblFacultad.getValueAt(1,2).toString());
           facultda3=Integer.parseInt(tblFacultad.getValueAt(2,2).toString());
            Facultda4=Integer.parseInt(tblFacultad.getValueAt(3,2).toString());
            Facultad5=Integer.parseInt(tblFacultad.getValueAt(4,2).toString());
             facultad6=Integer.parseInt(tblFacultad.getValueAt(5,2).toString());
             facultad7=Integer.parseInt(tblFacultad.getValueAt(6,2).toString());
         facultad8=Integer.parseInt(tblFacultad.getValueAt(7,2).toString());
         
        JFreeChart barra=null;
        DefaultCategoryDataset datos;
        
        datos = new DefaultCategoryDataset();

        datos.setValue(facultad1,tblFacultad.getValueAt(0,0).toString(),"");
        datos.setValue(facultdad2,tblFacultad.getValueAt(1,0).toString(),"");
          datos.setValue(facultda3,tblFacultad.getValueAt(2,0).toString(),"");
          datos.setValue(Facultda4,tblFacultad.getValueAt(3,0).toString(),"");
          datos.setValue(Facultad5,tblFacultad.getValueAt(4,0).toString(),"");
          datos.setValue(facultad6,tblFacultad.getValueAt(5,0).toString(),"");
            datos.setValue(facultad7,tblFacultad.getValueAt(6,0).toString(),"");
            datos.setValue(facultad8,tblFacultad.getValueAt(7,0).toString(),"");
          
       // datos.setValue(5,"electronica","");
       
        barra =ChartFactory.createBarChart3D("grafico de mas asistentes","EStudiantes","Cantidad",datos,PlotOrientation.VERTICAL,true,true,true);
       
        BufferedImage grafico= barra.createBufferedImage(panelcontenido.getWidth(),panelcontenido.getHeight());
        lblgrafico.setSize(panelcontenido.getSize());
        lblgrafico.setIcon(new ImageIcon(grafico));
        panelcontenido.updateUI();
    }
    public void grafico9()
    {
        
     int facultad1=0,facultdad2=0,facultda3=0,Facultda4=0,Facultad5=0,facultad6=0,facultad7,facultad8,facultad9;
     
//        
//        
//        for (int i = 0; i < tblFacultad.getRowCount();i++) {
//            facultad1=Integer.parseInt(tblFacultad.getValueAt(i,3).toString());
//        }
         facultad1=Integer.parseInt(tblFacultad.getValueAt(0,2).toString());
           facultdad2=Integer.parseInt(tblFacultad.getValueAt(1,2).toString());
           facultda3=Integer.parseInt(tblFacultad.getValueAt(2,2).toString());
            Facultda4=Integer.parseInt(tblFacultad.getValueAt(3,2).toString());
            Facultad5=Integer.parseInt(tblFacultad.getValueAt(4,2).toString());
             facultad6=Integer.parseInt(tblFacultad.getValueAt(5,2).toString());
             facultad7=Integer.parseInt(tblFacultad.getValueAt(6,2).toString());
         facultad8=Integer.parseInt(tblFacultad.getValueAt(7,2).toString());
          facultad9=Integer.parseInt(tblFacultad.getValueAt(8,2).toString());
         
        JFreeChart barra=null;
        DefaultCategoryDataset datos;
        
        datos = new DefaultCategoryDataset();

        datos.setValue(facultad1,tblFacultad.getValueAt(0,0).toString(),"");
        datos.setValue(facultdad2,tblFacultad.getValueAt(1,0).toString(),"");
          datos.setValue(facultda3,tblFacultad.getValueAt(2,0).toString(),"");
          datos.setValue(Facultda4,tblFacultad.getValueAt(3,0).toString(),"");
          datos.setValue(Facultad5,tblFacultad.getValueAt(4,0).toString(),"");
          datos.setValue(facultad6,tblFacultad.getValueAt(5,0).toString(),"");
            datos.setValue(facultad7,tblFacultad.getValueAt(6,0).toString(),"");
            datos.setValue(facultad8,tblFacultad.getValueAt(7,0).toString(),"");
              datos.setValue(facultad9,tblFacultad.getValueAt(8,0).toString(),"");
          
       // datos.setValue(5,"electronica","");
       
        barra =ChartFactory.createBarChart3D("grafico de mas asistentes","EStudiantes","Cantidad",datos,PlotOrientation.VERTICAL,true,true,true);
       
        BufferedImage grafico= barra.createBufferedImage(panelcontenido.getWidth(),panelcontenido.getHeight());
        lblgrafico.setSize(panelcontenido.getSize());
        lblgrafico.setIcon(new ImageIcon(grafico));
        panelcontenido.updateUI();
    }   
  public void grafico10()
    {
        
     int facultad1=0,facultdad2=0,facultda3=0,Facultda4=0,Facultad5=0,facultad6=0,facultad7,facultad8,facultad9,facultad10=0;
     
//        
//        
//        for (int i = 0; i < tblFacultad.getRowCount();i++) {
//            facultad1=Integer.parseInt(tblFacultad.getValueAt(i,3).toString());
//        }
         facultad1=Integer.parseInt(tblFacultad.getValueAt(0,2).toString());
           facultdad2=Integer.parseInt(tblFacultad.getValueAt(1,2).toString());
           facultda3=Integer.parseInt(tblFacultad.getValueAt(2,2).toString());
            Facultda4=Integer.parseInt(tblFacultad.getValueAt(3,2).toString());
            Facultad5=Integer.parseInt(tblFacultad.getValueAt(4,2).toString());
             facultad6=Integer.parseInt(tblFacultad.getValueAt(5,2).toString());
             facultad7=Integer.parseInt(tblFacultad.getValueAt(6,2).toString());
         facultad8=Integer.parseInt(tblFacultad.getValueAt(7,2).toString());
          facultad9=Integer.parseInt(tblFacultad.getValueAt(8,2).toString());
           facultad10=Integer.parseInt(tblFacultad.getValueAt(9,2).toString());
         
        JFreeChart barra=null;
        DefaultCategoryDataset datos;
        
        datos = new DefaultCategoryDataset();

        datos.setValue(facultad1,tblFacultad.getValueAt(0,0).toString(),"");
        datos.setValue(facultdad2,tblFacultad.getValueAt(1,0).toString(),"");
          datos.setValue(facultda3,tblFacultad.getValueAt(2,0).toString(),"");
          datos.setValue(Facultda4,tblFacultad.getValueAt(3,0).toString(),"");
          datos.setValue(Facultad5,tblFacultad.getValueAt(4,0).toString(),"");
          datos.setValue(facultad6,tblFacultad.getValueAt(5,0).toString(),"");
            datos.setValue(facultad7,tblFacultad.getValueAt(6,0).toString(),"");
            datos.setValue(facultad8,tblFacultad.getValueAt(7,0).toString(),"");
              datos.setValue(facultad9,tblFacultad.getValueAt(8,0).toString(),"");
              datos.setValue(facultad10,tblFacultad.getValueAt(9,0).toString(),"");
          
       // datos.setValue(5,"electronica","");
       
        barra =ChartFactory.createBarChart3D("grafico de mas asistentes","EStudiantes","Cantidad",datos,PlotOrientation.VERTICAL,true,true,true);
       
        BufferedImage grafico= barra.createBufferedImage(panelcontenido.getWidth(),panelcontenido.getHeight());
        lblgrafico.setSize(panelcontenido.getSize());
        lblgrafico.setIcon(new ImageIcon(grafico));
        panelcontenido.updateUI();
    }     
  
 public void grafico11()
    {
        
     int facultad1=0,facultdad2=0,facultda3=0,Facultda4=0,Facultad5=0,facultad6=0,facultad7,facultad8,facultad9,facultad10=0,facultad11;
     
//        
//        
//        for (int i = 0; i < tblFacultad.getRowCount();i++) {
//            facultad1=Integer.parseInt(tblFacultad.getValueAt(i,3).toString());
//        }
         facultad1=Integer.parseInt(tblFacultad.getValueAt(0,2).toString());
           facultdad2=Integer.parseInt(tblFacultad.getValueAt(1,2).toString());
           facultda3=Integer.parseInt(tblFacultad.getValueAt(2,2).toString());
            Facultda4=Integer.parseInt(tblFacultad.getValueAt(3,2).toString());
            Facultad5=Integer.parseInt(tblFacultad.getValueAt(4,2).toString());
             facultad6=Integer.parseInt(tblFacultad.getValueAt(5,2).toString());
             facultad7=Integer.parseInt(tblFacultad.getValueAt(6,2).toString());
         facultad8=Integer.parseInt(tblFacultad.getValueAt(7,2).toString());
          facultad9=Integer.parseInt(tblFacultad.getValueAt(8,2).toString());
           facultad10=Integer.parseInt(tblFacultad.getValueAt(9,2).toString());
            facultad11=Integer.parseInt(tblFacultad.getValueAt(10,2).toString());
         
        JFreeChart barra=null;
        DefaultCategoryDataset datos;
        
        datos = new DefaultCategoryDataset();

        datos.setValue(facultad1,tblFacultad.getValueAt(0,0).toString(),"");
        datos.setValue(facultdad2,tblFacultad.getValueAt(1,0).toString(),"");
          datos.setValue(facultda3,tblFacultad.getValueAt(2,0).toString(),"");
          datos.setValue(Facultda4,tblFacultad.getValueAt(3,0).toString(),"");
          datos.setValue(Facultad5,tblFacultad.getValueAt(4,0).toString(),"");
          datos.setValue(facultad6,tblFacultad.getValueAt(5,0).toString(),"");
            datos.setValue(facultad7,tblFacultad.getValueAt(6,0).toString(),"");
            datos.setValue(facultad8,tblFacultad.getValueAt(7,0).toString(),"");
              datos.setValue(facultad9,tblFacultad.getValueAt(8,0).toString(),"");
              datos.setValue(facultad10,tblFacultad.getValueAt(9,0).toString(),"");
                datos.setValue(facultad11,tblFacultad.getValueAt(10,0).toString(),"");
          
       // datos.setValue(5,"electronica","");
       
        barra =ChartFactory.createBarChart3D("grafico de mas asistentes","EStudiantes","Cantidad",datos,PlotOrientation.VERTICAL,true,true,true);
       
        BufferedImage grafico= barra.createBufferedImage(panelcontenido.getWidth(),panelcontenido.getHeight());
        lblgrafico.setSize(panelcontenido.getSize());
        lblgrafico.setIcon(new ImageIcon(grafico));
        panelcontenido.updateUI();
    }      
 
 public void grafico12()
    {
        
     int facultad1=0,facultdad2=0,facultda3=0,Facultda4=0,Facultad5=0,facultad6=0,facultad7,facultad8,facultad9,facultad10=0,facultad11,facultad12;
     
//        
//        
//        for (int i = 0; i < tblFacultad.getRowCount();i++) {
//            facultad1=Integer.parseInt(tblFacultad.getValueAt(i,3).toString());
//        }
         facultad1=Integer.parseInt(tblFacultad.getValueAt(0,2).toString());
           facultdad2=Integer.parseInt(tblFacultad.getValueAt(1,2).toString());
           facultda3=Integer.parseInt(tblFacultad.getValueAt(2,2).toString());
            Facultda4=Integer.parseInt(tblFacultad.getValueAt(3,2).toString());
            Facultad5=Integer.parseInt(tblFacultad.getValueAt(4,2).toString());
             facultad6=Integer.parseInt(tblFacultad.getValueAt(5,2).toString());
             facultad7=Integer.parseInt(tblFacultad.getValueAt(6,2).toString());
         facultad8=Integer.parseInt(tblFacultad.getValueAt(7,2).toString());
          facultad9=Integer.parseInt(tblFacultad.getValueAt(8,2).toString());
           facultad10=Integer.parseInt(tblFacultad.getValueAt(9,2).toString());
            facultad11=Integer.parseInt(tblFacultad.getValueAt(10,2).toString());
             facultad12=Integer.parseInt(tblFacultad.getValueAt(11,2).toString());
         
        JFreeChart barra=null;
        DefaultCategoryDataset datos;
        
        datos = new DefaultCategoryDataset();

        datos.setValue(facultad1,tblFacultad.getValueAt(0,0).toString(),"");
        datos.setValue(facultdad2,tblFacultad.getValueAt(1,0).toString(),"");
          datos.setValue(facultda3,tblFacultad.getValueAt(2,0).toString(),"");
          datos.setValue(Facultda4,tblFacultad.getValueAt(3,0).toString(),"");
          datos.setValue(Facultad5,tblFacultad.getValueAt(4,0).toString(),"");
          datos.setValue(facultad6,tblFacultad.getValueAt(5,0).toString(),"");
            datos.setValue(facultad7,tblFacultad.getValueAt(6,0).toString(),"");
            datos.setValue(facultad8,tblFacultad.getValueAt(7,0).toString(),"");
              datos.setValue(facultad9,tblFacultad.getValueAt(8,0).toString(),"");
              datos.setValue(facultad10,tblFacultad.getValueAt(9,0).toString(),"");
                datos.setValue(facultad11,tblFacultad.getValueAt(10,0).toString(),"");
                datos.setValue(facultad12,tblFacultad.getValueAt(11,0).toString(),"");
          
       // datos.setValue(5,"electronica","");
       
        barra =ChartFactory.createBarChart3D("grafico de mas asistentes","EStudiantes","Cantidad",datos,PlotOrientation.VERTICAL,true,true,true);
       
        BufferedImage grafico= barra.createBufferedImage(panelcontenido.getWidth(),panelcontenido.getHeight());
        lblgrafico.setSize(panelcontenido.getSize());
        lblgrafico.setIcon(new ImageIcon(grafico));
        panelcontenido.updateUI();
    }       
public void grafico13()
    {
        
     int facultad1=0,facultdad2=0,facultda3=0,Facultda4=0,Facultad5=0,facultad6=0,facultad7,facultad8,facultad9,facultad10=0,facultad11,facultad12,facultad13=0;
     
//        
//        
//        for (int i = 0; i < tblFacultad.getRowCount();i++) {
//            facultad1=Integer.parseInt(tblFacultad.getValueAt(i,3).toString());
//        }
         facultad1=Integer.parseInt(tblFacultad.getValueAt(0,2).toString());
           facultdad2=Integer.parseInt(tblFacultad.getValueAt(1,2).toString());
           facultda3=Integer.parseInt(tblFacultad.getValueAt(2,2).toString());
            Facultda4=Integer.parseInt(tblFacultad.getValueAt(3,2).toString());
            Facultad5=Integer.parseInt(tblFacultad.getValueAt(4,2).toString());
             facultad6=Integer.parseInt(tblFacultad.getValueAt(5,2).toString());
             facultad7=Integer.parseInt(tblFacultad.getValueAt(6,2).toString());
         facultad8=Integer.parseInt(tblFacultad.getValueAt(7,2).toString());
          facultad9=Integer.parseInt(tblFacultad.getValueAt(8,2).toString());
           facultad10=Integer.parseInt(tblFacultad.getValueAt(9,2).toString());
            facultad11=Integer.parseInt(tblFacultad.getValueAt(10,2).toString());
             facultad12=Integer.parseInt(tblFacultad.getValueAt(11,2).toString());
             facultad13=Integer.parseInt(tblFacultad.getValueAt(12,2).toString());
         
        JFreeChart barra=null;
        DefaultCategoryDataset datos;
        
        datos = new DefaultCategoryDataset();

        datos.setValue(facultad1,tblFacultad.getValueAt(0,0).toString(),"");
        datos.setValue(facultdad2,tblFacultad.getValueAt(1,0).toString(),"");
          datos.setValue(facultda3,tblFacultad.getValueAt(2,0).toString(),"");
          datos.setValue(Facultda4,tblFacultad.getValueAt(3,0).toString(),"");
          datos.setValue(Facultad5,tblFacultad.getValueAt(4,0).toString(),"");
          datos.setValue(facultad6,tblFacultad.getValueAt(5,0).toString(),"");
            datos.setValue(facultad7,tblFacultad.getValueAt(6,0).toString(),"");
            datos.setValue(facultad8,tblFacultad.getValueAt(7,0).toString(),"");
              datos.setValue(facultad9,tblFacultad.getValueAt(8,0).toString(),"");
              datos.setValue(facultad10,tblFacultad.getValueAt(9,0).toString(),"");
                datos.setValue(facultad11,tblFacultad.getValueAt(10,0).toString(),"");
                datos.setValue(facultad12,tblFacultad.getValueAt(11,0).toString(),"");
                  datos.setValue(facultad13,tblFacultad.getValueAt(12,0).toString(),"");
          
       // datos.setValue(5,"electronica","");
       
        barra =ChartFactory.createBarChart3D("grafico de mas asistentes","EStudiantes","Cantidad",datos,PlotOrientation.VERTICAL,true,true,true);
       
        BufferedImage grafico= barra.createBufferedImage(panelcontenido.getWidth(),panelcontenido.getHeight());
        lblgrafico.setSize(panelcontenido.getSize());
        lblgrafico.setIcon(new ImageIcon(grafico));
        panelcontenido.updateUI();
    }        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblgrafico;
    private javax.swing.JPanel panelcontenido;
    private javax.swing.JTable tblFacultad;
    // End of variables declaration//GEN-END:variables
}
