/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import Entidad.ClsDatos;
import Entidad.ClsEntFacultad;
import Negocio.ClsNegFacultdad;
import java.awt.image.BufferedImage;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.util.TableOrder;


/**
 *
 * @author usuario
 */
public class pnlConsultaFacultad extends javax.swing.JPanel {
           List <ClsDatos> Datoss=new ArrayList<ClsDatos>();
           
           List<String> Datoss2 = new ArrayList<String>();
           
    /**
     * Creates new form pnlConsultaFacultad
     */
    public pnlConsultaFacultad() {
        initComponents();
         Listar();
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblFacultad = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        panelcontenido = new javax.swing.JPanel();
        lblgrafico = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        tblFacultad.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblFacultad);

        jButton1.setText("Genrar Grafico");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        panelcontenido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout panelcontenidoLayout = new javax.swing.GroupLayout(panelcontenido);
        panelcontenido.setLayout(panelcontenidoLayout);
        panelcontenidoLayout.setHorizontalGroup(
            panelcontenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelcontenidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblgrafico, javax.swing.GroupLayout.DEFAULT_SIZE, 729, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelcontenidoLayout.setVerticalGroup(
            panelcontenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelcontenidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblgrafico, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton2.setText("graficar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelcontenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1)
                                .addGap(11, 11, 11)))
                        .addContainerGap(91, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(139, 139, 139))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(panelcontenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
 int cantidadfilas=0;
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        cantidadfilas=tblFacultad.getRowCount();
        if (cantidadfilas==2) {
            grafico1();
        }
        if (cantidadfilas==3) {
            grafico2();
        }
        if (cantidadfilas==4) {
            grafico3();
        }
        if (cantidadfilas==5) {
            grafico4();
        }
        if (cantidadfilas==6) {
            grafico5();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
     // graficar();
      Graficar2();
      
    }//GEN-LAST:event_jButton2ActionPerformed

    public void  Listar()
    {
      String titulo[]={"facultda","id","CAntidad",};
      
        ClsNegFacultdad empleados=new ClsNegFacultdad();
        ArrayList<ClsEntFacultad> facultdad=empleados.ListarFacultdad2();
        Iterator iterator=facultdad.iterator();
        DefaultTableModel dtm=new DefaultTableModel(null,titulo);
        
        String columna[]=new String[8];
        while (iterator.hasNext()) {
            ClsEntFacultad facultdade=new ClsEntFacultad();
            facultdade=(ClsEntFacultad) iterator.next();
            columna[0]=facultdade.getNombre_facu();
            columna[1]=String.valueOf(facultdade.getId_facu());
            columna[2]=String.valueOf(facultdade.getCantidad());
            
     
            dtm.addRow(columna);
        }
        tblFacultad.setModel(dtm);   
        
        
        
          for (int i = 0; i < tblFacultad.getRowCount(); i++) {
            ClsDatos o = new  ClsDatos();
            o.facultad=tblFacultad.getValueAt(i, 0).toString();
            o.cantidad=tblFacultad.getValueAt(i, 2).toString();
            Datoss.add(o);
            
        }
          
        for (int i = 0; i < tblFacultad.getRowCount(); i++) {
            
            Datoss2.add(tblFacultad.getValueAt(i, 0).toString());
             Datoss2.add(tblFacultad.getValueAt(i, 2).toString());
            
        }
   
    }
    
    public void graficar()
    {
//         JFreeChart barra=null;
//        DefaultCategoryDataset datos;
//            
//        datos = new DefaultCategoryDataset();
//          for (int i = 0; i <Datoss.size(); i++) {
//        
//
//       datos.setValue(Datoss.get(i).getCantidad(),Datoss.get(i).getFacultad(),"");
//       
//        }
//      // barra =ChartFactory.createBarChart3D("grafico de mas asistentes","EStudiantes","Cantidad",datos,PlotOrientation.VERTICAL,true,true,true);
//       barra=ChartFactory.createMultiplePieChart("grafico de mas asistenteEStudiantes Cantidad", datos, TableOrder.BY_ROW, true, true, true);
//        BufferedImage grafico= barra.createBufferedImage(panelcontenido.getWidth(),panelcontenido.getHeight());
//        lblgrafico.setSize(panelcontenido.getSize());
//        lblgrafico.setIcon(new ImageIcon(grafico));
//        panelcontenido.updateUI();
    }
    
    public void Graficar2()
    {

        JFreeChart barra=null;
        DefaultCategoryDataset datos;
            
        datos = new DefaultCategoryDataset();


        for (ClsDatos item : Datoss)
        {
                
        datos.setValue(Integer.parseInt(item.getCantidad()),item.getFacultad(),"");
        }
       barra =ChartFactory.createBarChart3D("grafico de mas asistentes","EStudiantes","Cantidad",datos,PlotOrientation.VERTICAL,true,true,true);
      // barra=ChartFactory.createMultiplePieChart("grafico de mas asistenteEStudiantes", datos, TableOrder.BY_ROW, true, true, true);
        BufferedImage grafico= barra.createBufferedImage(panelcontenido.getWidth(),panelcontenido.getHeight());
        lblgrafico.setSize(panelcontenido.getSize());
        lblgrafico.setIcon(new ImageIcon(grafico));
        panelcontenido.updateUI();
    }
    
   public void grafico1()
    {
        
                List<String> list = new ArrayList<String>();

        // Añadimos elementos
                list.add("Victor");
                list.add("Amaya");
                list.add("Julio");

                for (String nombre: list)
                  System.out.println(nombre);
        
//     int facultad1=0,facultdad2=0,facultda3;
//
//         facultad1=Integer.parseInt(tblFacultad.getValueAt(0,2).toString());
//           facultdad2=Integer.parseInt(tblFacultad.getValueAt(1,2).toString());
//        
//        JFreeChart barra=null;
//        DefaultCategoryDataset datos;
//        
//        datos = new DefaultCategoryDataset();
//
//        datos.setValue(facultad1,tblFacultad.getValueAt(0,0).toString(),"");
//        datos.setValue(facultdad2,tblFacultad.getValueAt(1,0).toString(),"");
//       // datos.setValue(5,"electronica","");
//       
//        barra =ChartFactory.createBarChart3D("grafico de mas asistentes","EStudiantes","Cantidad",datos,PlotOrientation.VERTICAL,true,true,true);
//       
//        BufferedImage grafico= barra.createBufferedImage(panelcontenido.getWidth(),panelcontenido.getHeight());
//        lblgrafico.setSize(panelcontenido.getSize());
//        lblgrafico.setIcon(new ImageIcon(grafico));
//        panelcontenido.updateUI();
    }
  public void grafico2()
    {
        
     int facultad1=0,facultdad2=0,facultda3=0;
  
         facultad1=Integer.parseInt(tblFacultad.getValueAt(0,2).toString());
           facultdad2=Integer.parseInt(tblFacultad.getValueAt(1,2).toString());
           facultda3=Integer.parseInt(tblFacultad.getValueAt(2,2).toString());
        
        JFreeChart barra=null;
        DefaultCategoryDataset datos;
        
        datos = new DefaultCategoryDataset();

        datos.setValue(facultad1,tblFacultad.getValueAt(0,0).toString(),"");
        datos.setValue(facultdad2,tblFacultad.getValueAt(1,0).toString(),"");
          datos.setValue(facultda3,tblFacultad.getValueAt(2,0).toString(),"");
          
       // datos.setValue(5,"electronica","");
       
        barra =ChartFactory.createBarChart3D("grafico de mas asistentes","EStudiantes","Cantidad",datos,PlotOrientation.VERTICAL,true,true,true);
       
        BufferedImage grafico= barra.createBufferedImage(panelcontenido.getWidth(),panelcontenido.getHeight());
        lblgrafico.setSize(panelcontenido.getSize());
        lblgrafico.setIcon(new ImageIcon(grafico));
        panelcontenido.updateUI();
    }
    public void grafico3()
    {
        
     int facultad1=0,facultdad2=0,facultda3=0,facultad4=0;
  
         facultad1=Integer.parseInt(tblFacultad.getValueAt(0,2).toString());
           facultdad2=Integer.parseInt(tblFacultad.getValueAt(1,2).toString());
           facultda3=Integer.parseInt(tblFacultad.getValueAt(2,2).toString());
           facultad4=Integer.parseInt(tblFacultad.getValueAt(3,2).toString());
        
        JFreeChart barra=null;
        DefaultCategoryDataset datos;
        
        datos = new DefaultCategoryDataset();

        datos.setValue(facultad1,tblFacultad.getValueAt(0,0).toString(),"");
        datos.setValue(facultdad2,tblFacultad.getValueAt(1,0).toString(),"");
          datos.setValue(facultda3,tblFacultad.getValueAt(2,0).toString(),"");
           datos.setValue(facultad4,tblFacultad.getValueAt(3,0).toString(),"");
          
       // datos.setValue(5,"electronica","");
       
        barra =ChartFactory.createBarChart3D("grafico de mas asistentes","EStudiantes","Cantidad",datos,PlotOrientation.VERTICAL,true,true,true);
       
        BufferedImage grafico= barra.createBufferedImage(panelcontenido.getWidth(),panelcontenido.getHeight());
        lblgrafico.setSize(panelcontenido.getSize());
        lblgrafico.setIcon(new ImageIcon(grafico));
        panelcontenido.updateUI();
    }
    public void grafico4()
    {
        
     int facultad1=0,facultdad2=0,facultda3=0,facultad4=0,facultad5=0;
  
         facultad1=Integer.parseInt(tblFacultad.getValueAt(0,2).toString());
           facultdad2=Integer.parseInt(tblFacultad.getValueAt(1,2).toString());
           facultda3=Integer.parseInt(tblFacultad.getValueAt(2,2).toString());
           facultad4=Integer.parseInt(tblFacultad.getValueAt(3,2).toString());
           facultad5=Integer.parseInt(tblFacultad.getValueAt(4,2).toString());
        
        JFreeChart barra=null;
        DefaultCategoryDataset datos;
        
        datos = new DefaultCategoryDataset();

        datos.setValue(facultad1,tblFacultad.getValueAt(0,0).toString(),"");
        datos.setValue(facultdad2,tblFacultad.getValueAt(1,0).toString(),"");
          datos.setValue(facultda3,tblFacultad.getValueAt(2,0).toString(),"");
           datos.setValue(facultad4,tblFacultad.getValueAt(3,0).toString(),"");
            datos.setValue(facultad5,tblFacultad.getValueAt(4,0).toString(),"");
       // datos.setValue(5,"electronica","");
       
        barra =ChartFactory.createBarChart3D("grafico de mas asistentes","EStudiantes","Cantidad",datos,PlotOrientation.VERTICAL,true,true,true);
       
        BufferedImage grafico= barra.createBufferedImage(panelcontenido.getWidth(),panelcontenido.getHeight());
        lblgrafico.setSize(panelcontenido.getSize());
        lblgrafico.setIcon(new ImageIcon(grafico));
        panelcontenido.updateUI();
    }
    public void grafico5()
    {
        
     int facultad1=0,facultdad2=0,facultda3=0,facultad4=0,facultad5=0,facultad6;
  
         facultad1=Integer.parseInt(tblFacultad.getValueAt(0,2).toString());
           facultdad2=Integer.parseInt(tblFacultad.getValueAt(1,2).toString());
           facultda3=Integer.parseInt(tblFacultad.getValueAt(2,2).toString());
           facultad4=Integer.parseInt(tblFacultad.getValueAt(3,2).toString());
           facultad5=Integer.parseInt(tblFacultad.getValueAt(4,2).toString());
           facultad6=Integer.parseInt(tblFacultad.getValueAt(5,2).toString());
        
        JFreeChart barra=null;
        DefaultCategoryDataset datos;
        
        datos = new DefaultCategoryDataset();

        datos.setValue(facultad1,tblFacultad.getValueAt(0,0).toString(),"");
        datos.setValue(facultdad2,tblFacultad.getValueAt(1,0).toString(),"");
          datos.setValue(facultda3,tblFacultad.getValueAt(2,0).toString(),"");
           datos.setValue(facultad4,tblFacultad.getValueAt(3,0).toString(),"");
            datos.setValue(facultad5,tblFacultad.getValueAt(4,0).toString(),"");
             datos.setValue(facultad6,tblFacultad.getValueAt(5,0).toString(),"");
       // datos.setValue(5,"electronica","");
       
        barra =ChartFactory.createBarChart3D("grafico de mas asistentes","EStudiantes","Cantidad",datos,PlotOrientation.VERTICAL,true,true,true);
       
        BufferedImage grafico= barra.createBufferedImage(panelcontenido.getWidth(),panelcontenido.getHeight());
        lblgrafico.setSize(panelcontenido.getSize());
        lblgrafico.setIcon(new ImageIcon(grafico));
        panelcontenido.updateUI();
    }
    
      public void grafico6()
    {
        
     int facultad1=0,facultdad2=0,facultda3=0,facultad4=0,facultad5=0,facultad6,facultad7=0;
  
         facultad1=Integer.parseInt(tblFacultad.getValueAt(0,2).toString());
           facultdad2=Integer.parseInt(tblFacultad.getValueAt(1,2).toString());
           facultda3=Integer.parseInt(tblFacultad.getValueAt(2,2).toString());
           facultad4=Integer.parseInt(tblFacultad.getValueAt(3,2).toString());
           facultad5=Integer.parseInt(tblFacultad.getValueAt(4,2).toString());
           facultad6=Integer.parseInt(tblFacultad.getValueAt(5,2).toString());
           facultad7=Integer.parseInt(tblFacultad.getValueAt(6,2).toString());
        
        JFreeChart barra=null;
        DefaultCategoryDataset datos;
        
        datos = new DefaultCategoryDataset();

        datos.setValue(facultad1,tblFacultad.getValueAt(0,0).toString(),"");
        datos.setValue(facultdad2,tblFacultad.getValueAt(1,0).toString(),"");
          datos.setValue(facultda3,tblFacultad.getValueAt(2,0).toString(),"");
           datos.setValue(facultad4,tblFacultad.getValueAt(3,0).toString(),"");
            datos.setValue(facultad5,tblFacultad.getValueAt(4,0).toString(),"");
             datos.setValue(facultad6,tblFacultad.getValueAt(5,0).toString(),"");
             datos.setValue(facultad7,tblFacultad.getValueAt(6,0).toString(),"");
       // datos.setValue(5,"electronica","");
       
        barra =ChartFactory.createBarChart3D("grafico de mas asistentes","EStudiantes","Cantidad",datos,PlotOrientation.VERTICAL,true,true,true);
       
        BufferedImage grafico= barra.createBufferedImage(panelcontenido.getWidth(),panelcontenido.getHeight());
        lblgrafico.setSize(panelcontenido.getSize());
        lblgrafico.setIcon(new ImageIcon(grafico));
        panelcontenido.updateUI();
    }
      
       public void grafico7()
    {
        
     int facultad1=0,facultdad2=0,facultda3=0,facultad4=0,facultad5=0,facultad6,facultad7=0,facultad8;
  
         facultad1=Integer.parseInt(tblFacultad.getValueAt(0,2).toString());
           facultdad2=Integer.parseInt(tblFacultad.getValueAt(1,2).toString());
           facultda3=Integer.parseInt(tblFacultad.getValueAt(2,2).toString());
           facultad4=Integer.parseInt(tblFacultad.getValueAt(3,2).toString());
           facultad5=Integer.parseInt(tblFacultad.getValueAt(4,2).toString());
           facultad6=Integer.parseInt(tblFacultad.getValueAt(5,2).toString());
           facultad7=Integer.parseInt(tblFacultad.getValueAt(6,2).toString());
            facultad8=Integer.parseInt(tblFacultad.getValueAt(7,2).toString());
        
        JFreeChart barra=null;
        DefaultCategoryDataset datos;
        
        datos = new DefaultCategoryDataset();

        datos.setValue(facultad1,tblFacultad.getValueAt(0,0).toString(),"");
        datos.setValue(facultdad2,tblFacultad.getValueAt(1,0).toString(),"");
          datos.setValue(facultda3,tblFacultad.getValueAt(2,0).toString(),"");
           datos.setValue(facultad4,tblFacultad.getValueAt(3,0).toString(),"");
            datos.setValue(facultad5,tblFacultad.getValueAt(4,0).toString(),"");
             datos.setValue(facultad6,tblFacultad.getValueAt(5,0).toString(),"");
             datos.setValue(facultad7,tblFacultad.getValueAt(6,0).toString(),"");
               datos.setValue(facultad8,tblFacultad.getValueAt(7,0).toString(),"");
       // datos.setValue(5,"electronica","");
       
        barra =ChartFactory.createBarChart3D("grafico de mas asistentes","EStudiantes","Cantidad",datos,PlotOrientation.VERTICAL,true,true,true);
       
        BufferedImage grafico= barra.createBufferedImage(panelcontenido.getWidth(),panelcontenido.getHeight());
        lblgrafico.setSize(panelcontenido.getSize());
        lblgrafico.setIcon(new ImageIcon(grafico));
        panelcontenido.updateUI();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblgrafico;
    private javax.swing.JPanel panelcontenido;
    private javax.swing.JTable tblFacultad;
    // End of variables declaration//GEN-END:variables
}
