/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;
import Entidad.ClsEntEscuela;
import Negocio.ClsNegEscuela;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import principal.Principal;

import Negocio.ClsNegFacultdad;
import Entidad.ClsEntFacultad;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author gcoaquira
 */
public class pnlEscuela extends javax.swing.JPanel {
 static   ResultSet rs=null;
    /**
     * Creates new form pnlEscuela
     */
    public pnlEscuela() {
        initComponents();
        ListarEscuela();
        
        cargarcomFacultdad();
        cargarcombo2();
    }

    
    public void  ListarEscuela()

    {
         String titulo[]={"IdEscuela","Iniciales","Nombre",};
      
        ClsNegEscuela Escuela=new ClsNegEscuela();
        ArrayList<ClsEntEscuela> Escu=Escuela.ListarEscuela();
        Iterator iterator=Escu.iterator();
        DefaultTableModel dtm=new DefaultTableModel(null,titulo);
        
        String columna[]=new String[8];
        while (iterator.hasNext()) {
            ClsEntEscuela Escuelita=new ClsEntEscuela();
            Escuelita=(ClsEntEscuela) iterator.next();
            columna[0]=String.valueOf(Escuelita.getId_escu());
            columna[1]=Escuelita.getIniciales_escu();
            columna[2]=Escuelita.getNombre_escu();
     
            dtm.addRow(columna);
        }
        tblEscuela.setModel(dtm);   
        
    }
    
    
    int  intcontador;
     int idper[]=new int[100];
       void cargarcomFacultdad()
     {
         ClsNegFacultdad Escuela=new ClsNegFacultdad();
         ArrayList<ClsEntFacultad> Escu=Escuela.ListarFacultdad();
         Iterator iterator=Escu.iterator();
         DefaultComboBoxModel modelo=new DefaultComboBoxModel();
         
         modelo.removeAllElements();
         
         String columna[]=new String[3];
          intcontador=0;
          while (iterator.hasNext())
          {
              ClsEntFacultad objEscuela=new ClsEntFacultad();
              objEscuela=(ClsEntFacultad) iterator.next();              
              idper[intcontador]=objEscuela.getId_facu();
              columna[0]=objEscuela.getIniciales_facu();
              columna[1]=objEscuela.getNombre_facu();
            
              
               modelo.addElement(objEscuela.getNombre_facu());
               intcontador ++;
          }
          Cbofacultdad.setModel(modelo);
     }
       
        int  intcontador2;
     int idper2[]=new int[100];
    void cargarcombo2()
     {
         ClsNegFacultdad Escuela=new ClsNegFacultdad();
         ArrayList<ClsEntFacultad> Escu=Escuela.ListarFacultdad();
         Iterator iterator=Escu.iterator();
         DefaultComboBoxModel modelo1=new DefaultComboBoxModel();
         
         modelo1.removeAllElements();
         
         String columna[]=new String[3];
          intcontador2=0;
          while (iterator.hasNext())
          {
              ClsEntFacultad objEscuela=new ClsEntFacultad();
              objEscuela=(ClsEntFacultad) iterator.next();              
              idper2[intcontador2]=objEscuela.getId_facu();
              columna[0]=objEscuela.getIniciales_facu();
              columna[1]=objEscuela.getNombre_facu();
            
              
               modelo1.addElement(objEscuela.getNombre_facu());
                //  modelo1.addElement("Listar Todo");
               intcontador2 ++;
          }
          cboListar.setModel(modelo1);
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEscuela = new javax.swing.JTable();
        btnActualizar = new rscomponentshade.RSButtonShade();
        btnAgregar = new rscomponentshade.RSButtonShade();
        btnEliminar = new rscomponentshade.RSButtonShade();
        cboListar = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        btnAgregar1 = new rscomponentshade.RSButtonShade();
        jPanel1 = new javax.swing.JPanel();
        txtcodigoescuela = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtiniciales = new javax.swing.JTextField();
        btnGuardar = new rscomponentshade.RSButtonShade();
        btnCancelar = new rscomponentshade.RSButtonShade();
        Cbofacultdad = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2), "MANTENIMIENTO ESCUELA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(51, 51, 51))); // NOI18N

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "LISTA ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        tblEscuela.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tblEscuela.setForeground(new java.awt.Color(52, 73, 94));
        tblEscuela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblEscuela.setGridColor(new java.awt.Color(204, 204, 204));
        tblEscuela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEscuelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblEscuela);

        btnActualizar.setBackground(new java.awt.Color(6, 20, 51));
        btnActualizar.setText("Actualizar");
        btnActualizar.setBgHover(new java.awt.Color(10, 36, 95));
        btnActualizar.setBgShade(new java.awt.Color(255, 255, 255));
        btnActualizar.setBgShadeHover(new java.awt.Color(242, 187, 10));

        btnAgregar.setBackground(new java.awt.Color(6, 20, 51));
        btnAgregar.setText("LISTAR");
        btnAgregar.setBgHover(new java.awt.Color(10, 36, 95));
        btnAgregar.setBgShade(new java.awt.Color(255, 255, 255));
        btnAgregar.setBgShadeHover(new java.awt.Color(242, 187, 10));
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(6, 20, 51));
        btnEliminar.setText("Eliminar");
        btnEliminar.setBgHover(new java.awt.Color(10, 36, 95));
        btnEliminar.setBgShade(new java.awt.Color(255, 255, 255));
        btnEliminar.setBgShadeHover(new java.awt.Color(242, 187, 10));

        cboListar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cboListar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Facultadad de Ingenieria", "Facultadad de Arquitectura", "Facultadad de Derecho", "etc" }));
        cboListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboListarActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(10, 36, 95));
        jLabel11.setText("Listar por:");

        btnAgregar1.setBackground(new java.awt.Color(6, 20, 51));
        btnAgregar1.setText("Nuevo");
        btnAgregar1.setBgHover(new java.awt.Color(10, 36, 95));
        btnAgregar1.setBgShade(new java.awt.Color(255, 255, 255));
        btnAgregar1.setBgShadeHover(new java.awt.Color(242, 187, 10));
        btnAgregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnAgregar1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 39, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(cboListar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboListar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "DETALLE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        txtcodigoescuela.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtnombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(10, 36, 95));
        jLabel2.setText("Nombre:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(10, 36, 95));
        jLabel1.setText("Código:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(10, 36, 95));
        jLabel4.setText("Iniciales:");

        txtiniciales.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnGuardar.setBackground(new java.awt.Color(6, 20, 51));
        btnGuardar.setText("Guardar");
        btnGuardar.setBgHover(new java.awt.Color(10, 36, 95));
        btnGuardar.setBgShade(new java.awt.Color(255, 255, 255));
        btnGuardar.setBgShadeHover(new java.awt.Color(242, 187, 10));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(6, 20, 51));
        btnCancelar.setText("Cancelar");
        btnCancelar.setBgHover(new java.awt.Color(10, 36, 95));
        btnCancelar.setBgShade(new java.awt.Color(255, 255, 255));
        btnCancelar.setBgShadeHover(new java.awt.Color(242, 187, 10));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        Cbofacultdad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(10, 36, 95));
        jLabel10.setText("Facultad:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtnombre, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                            .addComponent(txtiniciales)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtcodigoescuela, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Cbofacultdad, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcodigoescuela, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cbofacultdad, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtiniciales, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 194, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(121, 121, 121))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 504, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblEscuelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEscuelaMouseClicked

    }//GEN-LAST:event_tblEscuelaMouseClicked

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        ListarEscuela();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        
        int Busqueda;
        Busqueda= Integer.parseInt(txtcodigoescuela.getText());     
        
        ClsNegEscuela Escuela = new ClsNegEscuela();
        try{            
            rs=Escuela.ConsultarEcuela(Busqueda);
            boolean encuentra =false;
            while(rs.next()){
             
                encuentra= true;
                 JOptionPane.showMessageDialog(null,"ya hay un codigo igual");
            }
            if(encuentra== false){
                    
               ClsEntEscuela o =new ClsEntEscuela();
            ClsNegEscuela ob=new ClsNegEscuela();

           o.setId_escu(Integer.parseInt(txtcodigoescuela.getText()));
            o.setId_facu(idper[Cbofacultdad.getSelectedIndex()]);  
            // o.setId_facu(1);
           o.setIniciales_escu(txtiniciales.getText());
           o.setNombre_escu(txtnombre.getText());
           ob.AgregarEscuela(o);
           ListarEscuela();
              JOptionPane.showMessageDialog(null,"Registrado");
                
                
                //JOptionPane.showMessageDialog(null,"No existen registros","Tabla Consultas",1);
            }

        }catch(Exception ex){
            ex.printStackTrace();
        }
        
//        
        
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        new CambiaPanel(Principal.pnlPrincipal, new paneles.pnlMantenimiento());
        Principal.lblTitulo.setText("   Mantenimiento del Sistema");
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void cboListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboListarActionPerformed
        // TODO add your handling code here:
           String titulo[]={"IdEscuela","Iniciales","Nombre",};
        
        ClsNegEscuela consumos=new ClsNegEscuela();
        
        ArrayList<ClsEntEscuela> empleado=consumos.ListarPorEscuela(idper2[cboListar.getSelectedIndex()]);
        Iterator iterator=empleado.iterator();
        DefaultTableModel dtm=new DefaultTableModel(null,titulo);
        
        String columna[]=new String[8];
        while (iterator.hasNext()) {
            ClsEntEscuela Escuelita=new ClsEntEscuela();
            Escuelita=(ClsEntEscuela) iterator.next();
             columna[0]=String.valueOf(Escuelita.getId_escu());
            columna[1]=Escuelita.getIniciales_escu();
            columna[2]=Escuelita.getNombre_escu();
     
            dtm.addRow(columna);
        }
        
        tblEscuela.setModel(dtm);
        
        
    }//GEN-LAST:event_cboListarActionPerformed

    private void btnAgregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregar1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Cbofacultdad;
    private rscomponentshade.RSButtonShade btnActualizar;
    private rscomponentshade.RSButtonShade btnAgregar;
    private rscomponentshade.RSButtonShade btnAgregar1;
    private rscomponentshade.RSButtonShade btnCancelar;
    private rscomponentshade.RSButtonShade btnEliminar;
    private rscomponentshade.RSButtonShade btnGuardar;
    private javax.swing.JComboBox<String> cboListar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEscuela;
    private javax.swing.JTextField txtcodigoescuela;
    private javax.swing.JTextField txtiniciales;
    private javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables
}
