/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import principal.Principal;

import Entidad.ClsEntEvento;
import Negocio.ClsNegEvento;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;


/**
 *
 * @author RojeruSan
 */
public class pnlEventos extends javax.swing.JPanel {
 String titulo[]={"codigo","Titulo","DEscripcion","Estado","Fecha","Hora inicio","Hora fin","Lugar","Responsable"};
         DefaultTableModel dtm=new DefaultTableModel(null,titulo);
    /**
     * Creates new form pnlHome
     */
    public pnlEventos() {
        initComponents();
        Listar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblEventos = new javax.swing.JTable();
        btnAgregar = new rscomponentshade.RSButtonShade();
        txtFiltro = new rscomponentshade.RSFormatFieldShade();
        btnActualizar = new rscomponentshade.RSButtonShade();
        btnEliminar = new rscomponentshade.RSButtonShade();
        btnPagar = new rscomponentshade.RSButtonShade();

        setBackground(new java.awt.Color(204, 204, 204));

        tblEventos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tblEventos.setForeground(new java.awt.Color(52, 73, 94));
        tblEventos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblEventos.setGridColor(new java.awt.Color(204, 204, 204));
        tblEventos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEventosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblEventos);

        btnAgregar.setBackground(new java.awt.Color(6, 20, 51));
        btnAgregar.setText("Agregar");
        btnAgregar.setBgHover(new java.awt.Color(10, 36, 95));
        btnAgregar.setBgShade(new java.awt.Color(255, 255, 255));
        btnAgregar.setBgShadeHover(new java.awt.Color(242, 187, 10));
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        txtFiltro.setPlaceholder("Filtrar eventos");
        txtFiltro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFiltroKeyTyped(evt);
            }
        });

        btnActualizar.setBackground(new java.awt.Color(6, 20, 51));
        btnActualizar.setText("Actualizar");
        btnActualizar.setBgHover(new java.awt.Color(10, 36, 95));
        btnActualizar.setBgShade(new java.awt.Color(255, 255, 255));
        btnActualizar.setBgShadeHover(new java.awt.Color(242, 187, 10));
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(6, 20, 51));
        btnEliminar.setText("Eliminar");
        btnEliminar.setBgHover(new java.awt.Color(10, 36, 95));
        btnEliminar.setBgShade(new java.awt.Color(255, 255, 255));
        btnEliminar.setBgShadeHover(new java.awt.Color(242, 187, 10));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnPagar.setBackground(new java.awt.Color(255, 0, 0));
        btnPagar.setBorder(null);
        btnPagar.setText("Iniciar Evento");
        btnPagar.setBgHover(new java.awt.Color(0, 204, 0));
        btnPagar.setBgShade(new java.awt.Color(204, 204, 204));
        btnPagar.setBgShadeHover(new java.awt.Color(204, 204, 204));
        btnPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 943, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    
    
     public void  Listar()

    {
            
      
        ClsNegEvento Evento=new ClsNegEvento();
        ArrayList<ClsEntEvento> Escu=Evento.ListarEvento();
        Iterator iterator=Escu.iterator();
        
        
        String columna[]=new String[10];
        while (iterator.hasNext()) {
            ClsEntEvento Eve=new ClsEntEvento();
            Eve=(ClsEntEvento) iterator.next();
            columna[0]=String.valueOf(Eve.getId_eve());
            columna[1]=Eve.getTitulo_eve();
            columna[2]=Eve.getDescripcion_eve();
             columna[3]=Eve.getEstado_eve();
             columna[4]=String.valueOf(Eve.getId_ubi());
            columna[5]=Eve.getFecha_eve();
             columna[6]=Eve.getHorainicio_eve();
            columna[7]=Eve.getHorafin_eve();
              columna[8]=String.valueOf(Eve.getId_respo());
              //columna[9]=Eve.getResponsable();
             
            dtm.addRow(columna);
        }
        tblEventos.setModel(dtm);   
    
        
    }
    
    
    private void tblEventosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEventosMouseClicked
        
    }//GEN-LAST:event_tblEventosMouseClicked

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        new CambiaPanel(Principal.pnlPrincipal, new paneles.pnlAgregarEvento());
        Principal.lblTitulo.setText("Registro de Nuevo Evento");
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed
 TableRowSorter trs;
    public String leerBusqueda(){
        String busca=txtFiltro.getText().trim().replace("", "");
        return busca;
    }
    private void txtFiltroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFiltroKeyTyped
        // TODO add your handling code here:
        
            
        txtFiltro.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent ke) {
                trs.setRowFilter(RowFilter.regexFilter("(?i)"+leerBusqueda(), 0,1,2,3,4,5,6)); //Filtra datos
            }
        });
        trs=new TableRowSorter(dtm);
        tblEventos.setRowSorter(trs);
    }//GEN-LAST:event_txtFiltroKeyTyped

    private void btnPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarActionPerformed
        principal.Asistencia f = new principal.Asistencia();
        //   f.show();        
        f.setVisible(true);
        
    }//GEN-LAST:event_btnPagarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rscomponentshade.RSButtonShade btnActualizar;
    private rscomponentshade.RSButtonShade btnAgregar;
    private rscomponentshade.RSButtonShade btnEliminar;
    private rscomponentshade.RSButtonShade btnGenerarRecibos;
    private rscomponentshade.RSButtonShade btnGenerarRecibos1;
    private rscomponentshade.RSButtonShade btnPagar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEventos;
    private rscomponentshade.RSFormatFieldShade txtFiltro;
    // End of variables declaration//GEN-END:variables
}
