/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import Entidad.ClsEntEvento;
import Negocio.ClsNegEvento;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.DefaultComboBoxModel;

import Entidad.ClsEntInvitados;
import Negocio.ClsNegInvitados;
import Entidad.ClsEntEstudiante;
import Negocio.ClsNegEstudiante;

import Entidad.ClsEntAsistentes;
import Negocio.ClsNegAsistentes;


import Entidad.ClsEntFacultadInvitada;
import Negocio.ClsNegFacultdadInvitada;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author usuario
 */
public class pnlIniciarEvento extends javax.swing.JPanel {
 static   ResultSet rs=null;
    /**
     * Creates new form pnlIniciarEvento
     */
    public pnlIniciarEvento() {
        initComponents();
        cargarcomEventos();
        jButton3.enable(false);
       // txtidescuela.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cboeventos = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblasis = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        txtcodigo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFacultades = new javax.swing.JTable();
        txtnombres = new javax.swing.JTextField();
        cboobservacion = new javax.swing.JComboBox<>();
        txtidescuela = new javax.swing.JTextField();
        btnAgregar2 = new rscomponentshade.RSButtonShade();
        txtescuela = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Nombres = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));

        cboeventos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboeventos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboeventosActionPerformed(evt);
            }
        });

        jButton2.setText("buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        tblasis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblasis);

        jButton3.setText("Buscar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        tblFacultades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblFacultades);

        cboobservacion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cboobservacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Asistio", "Asistio Borracho", "Asisto Drogado", "Aistio Tarde" }));

        btnAgregar2.setBackground(new java.awt.Color(6, 20, 51));
        btnAgregar2.setText("Registrar Asistencia");
        btnAgregar2.setBgHover(new java.awt.Color(10, 36, 95));
        btnAgregar2.setBgShade(new java.awt.Color(255, 255, 255));
        btnAgregar2.setBgShadeHover(new java.awt.Color(242, 187, 10));
        btnAgregar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(10, 36, 95));
        jLabel1.setText("Código:");

        Nombres.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Nombres.setForeground(new java.awt.Color(10, 36, 95));
        Nombres.setText("Nombres");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(10, 36, 95));
        jLabel2.setText("Escuela");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(10, 36, 95));
        jLabel3.setText("Observacion");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jLabel1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Nombres)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtcodigo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                                        .addComponent(txtnombres, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(txtescuela, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cboobservacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnAgregar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtidescuela, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cboeventos, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboeventos, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtnombres, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Nombres, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtescuela, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cboobservacion, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAgregar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtidescuela, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
    }// </editor-fold>//GEN-END:initComponents
        int  intcontador;
       int idper[]=new int[100];
    void cargarcomEventos()
     {
         ClsNegEvento Evento=new ClsNegEvento();
         ArrayList<ClsEntEvento> Eve=Evento.ListarEvento();
         Iterator iterator=Eve.iterator();
         DefaultComboBoxModel modelo=new DefaultComboBoxModel();
         
         modelo.removeAllElements();
         
         String columna[]=new String[3];
          intcontador=0;
          while (iterator.hasNext())
          {
              ClsEntEvento Even=new ClsEntEvento();
              Even=(ClsEntEvento) iterator.next();              
              idper[intcontador]=Even.getId_eve();
              columna[0]=String.valueOf(Even.getId_eve());
              columna[1]=Even.getTitulo_eve();              
               modelo.addElement(Even.getTitulo_eve());
               intcontador ++;
          }
          cboeventos.setModel(modelo);
     }
    private void cboeventosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboeventosActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cboeventosActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         jButton3.enable(true);
        buscar();
        buscar2();
//        Guardar2();
//
//        buscarAsitentes2();

    }//GEN-LAST:event_jButton2ActionPerformed

    public void buscar()
    {
        String titulo[]={"Escuela","Codigo","nombre","Estado"};

        ClsNegInvitados consumos=new ClsNegInvitados();
//import Entidad.ClsEntInvitados;
//import Negocio.ClsNegInvitados;
        ArrayList<ClsEntInvitados> empleado=consumos.ListarIvitadosAEvento(idper[cboeventos.getSelectedIndex()]);
        JOptionPane.showMessageDialog(null,idper[cboeventos.getSelectedIndex()]);
        Iterator iterator=empleado.iterator();
        DefaultTableModel dtm=new DefaultTableModel(null,titulo);

        String columna[]=new String[5];
        while (iterator.hasNext()) {
            ClsEntInvitados Asis=new ClsEntInvitados();
            Asis=(ClsEntInvitados) iterator.next();
            columna[0]=Asis.getNombre_escu();
            columna[1]=String.valueOf(Asis.getId_estu());
            columna[2]=Asis.getNombre_estu();
            columna[3]=Asis.getEstado();
                    

            dtm.addRow(columna);
        }
//
        tblasis.setModel(dtm);
    }
    public void buscar2()
    {
       // ListarFacultadInvitadaEventoimport Entidad.ClsEntFacultadInvitada;
//import Negocio.ClsNegFacultdadInvitada;
                
        String titulo[]={"Facultad","Escuela"};

        ClsNegFacultdadInvitada Facult=new ClsNegFacultdadInvitada();
//import Entidad.ClsEntInvitados;
//import Negocio.ClsNegInvitados;
        ArrayList<ClsEntFacultadInvitada> empleado=Facult.ListarFacultadInvitadaEvento(idper[cboeventos.getSelectedIndex()]);
        JOptionPane.showMessageDialog(null,idper[cboeventos.getSelectedIndex()]);
        Iterator iterator=empleado.iterator();
        DefaultTableModel dtm1=new DefaultTableModel(null,titulo);

        String columna[]=new String[3];
        while (iterator.hasNext()) {
            ClsEntFacultadInvitada Asis=new ClsEntFacultadInvitada();
            Asis=(ClsEntFacultadInvitada) iterator.next();
            columna[0]=Asis.getNombre_facu();
            columna[1]=Asis.getNombre_escu();
          
                
            dtm1.addRow(columna);
        }
//
        tblFacultades.setModel(dtm1);
                
    }
            
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        BuscarSiEstalistaInvitados();
        
//        for (int i = 0; i <tblasis.getRowCount(); i++) {
//            if (txtcodigo.getText().equals(tblasis.getValueAt(i,1).toString())) {
//                BusquedaEstudiante();
//            }
//            else
//            {
//                JOptionPane.showMessageDialog(null,"No estas en la Lista Wey");
//               
//                BusquedaEstudiante();
//                 break;
//            }
//        }
// NO MOVER ESTO WEY
//        int codigo;
//        codigo=Integer.parseInt(txtcodigo.getText());
//
//        ClsEntInvitados o =  new  ClsEntInvitados();
//        ClsNegInvitados ob = new ClsNegInvitados();
//        
//        o.setId_estu(codigo);
//        o.setEstado("Asistio");
//        ob.ModificarAsistente(idper[cboeventos.getSelectedIndex()],codigo, o);
//         buscar();
         
     

    }//GEN-LAST:event_jButton3ActionPerformed

    boolean existe=false;
    
    public void BusquedaEstudiante()
    {   int Busqueda;
        Busqueda= Integer.parseInt(txtcodigo.getText());        
        ClsNegEstudiante Estu = new ClsNegEstudiante();
        
        try{
            
            rs=Estu.ConsultarEstudiante2(Busqueda);
            boolean encuentra =false;
            while(rs.next()){
                txtnombres.setText((String) rs.getString(2));
                txtidescuela.setText((String)rs.getString(3));
                txtescuela.setText((String)rs.getString(4));
                encuentra= true;

            }
            if(encuentra== false){
                JOptionPane.showMessageDialog(null,"No existen registros","Tabla Consultas",1);
            }

        }catch(Exception ex){
            ex.printStackTrace();
        }
        
    
    }

public void BuscarSiEstalistaInvitados()
{
        int Busqueda;
        Busqueda= Integer.parseInt(txtcodigo.getText());    
        boolean encuentra =false; 
        ClsNegInvitados Escuela = new ClsNegInvitados();
        try{            
            rs=Escuela.ConsultarInvitados(idper[cboeventos.getSelectedIndex()],Busqueda);
           
            while(rs.next()){
             
                encuentra= true;
                BusquedaEstudiante();
                existe=true;
            }
            if(encuentra== false){
                   
              JOptionPane.showMessageDialog(null,"No estas en La Lista Wey");
               BusquedaEstudiante();
               existe=false;
                
            }

        }catch(Exception ex){
            ex.printStackTrace();
        }
        
}
    private void btnAgregar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar2ActionPerformed
       try {
           if (existe==false) {
                GuardarAsistencia();
        }
        else{

             
            int codigo;
            codigo=Integer.parseInt(txtcodigo.getText());

            ClsEntInvitados o =  new  ClsEntInvitados();
            ClsNegInvitados ob = new ClsNegInvitados();

            o.setId_estu(codigo);
            o.setEstado("Asistio");
            ob.ModificarAsistente(idper[cboeventos.getSelectedIndex()],codigo, o);
             buscar();
             GuardarAsistencia();
        }
       }catch (Exception ex){
     JOptionPane.showMessageDialog(null,"Algo Salio Mal");
    }
        
    }//GEN-LAST:event_btnAgregar2ActionPerformed

public void  GuardarAsistencia()
{
    ClsEntAsistentes obje = new ClsEntAsistentes();
        ClsNegAsistentes obneg = new ClsNegAsistentes();
        obje.setId_eve(idper[cboeventos.getSelectedIndex()]);
        obje.setCodigo_estu(Integer.parseInt(txtcodigo.getText()));
        obje.setId_escu(Integer.parseInt(txtidescuela.getText()));
        obje.setObservacion_asis(cboobservacion.getSelectedItem().toString());
        obneg.AgregarAsistentes(obje);
        JOptionPane.showMessageDialog(null,"Registrado WEy");
        txtcodigo.setText("");
        txtescuela.setText("");
        
}
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Nombres;
    private rscomponentshade.RSButtonShade btnAgregar2;
    private javax.swing.JComboBox<String> cboeventos;
    private javax.swing.JComboBox<String> cboobservacion;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblFacultades;
    private javax.swing.JTable tblasis;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtescuela;
    private javax.swing.JTextField txtidescuela;
    private javax.swing.JTextField txtnombres;
    // End of variables declaration//GEN-END:variables
}
