/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import Entidad.ClsEntAsistentes;
import Negocio.ClsNegAsistentes;
import Entidad.ClsEntEvento;
import Negocio.ClsNegEvento;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;


public class pnlListaAsistenes extends javax.swing.JPanel {

    /**
     * Creates new form pnlListaAsistenes
     */
    public pnlListaAsistenes() {
        initComponents();
        cargarcomEventos();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cboeventos = new javax.swing.JComboBox<>();
        txtFiltro = new rscomponentshade.RSFormatFieldShade();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAsistentes = new javax.swing.JTable();

        cboeventos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cboeventos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboeventosActionPerformed(evt);
            }
        });

        txtFiltro.setPlaceholder("Filtrar Estudiante");
        txtFiltro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFiltroKeyTyped(evt);
            }
        });

        tblAsistentes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblAsistentes);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(cboeventos, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 816, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboeventos, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(115, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    int  intcontador;
       int idper[]=new int[100];
    void cargarcomEventos()
     {
         ClsNegEvento Evento=new ClsNegEvento();
         ArrayList<ClsEntEvento> Eve=Evento.ListarEvento();
         Iterator iterator=Eve.iterator();
         DefaultComboBoxModel modelo=new DefaultComboBoxModel();
         
         modelo.removeAllElements();
         
         String columna[]=new String[3];
          intcontador=0;
          while (iterator.hasNext())
          {
              ClsEntEvento Even=new ClsEntEvento();
              Even=(ClsEntEvento) iterator.next();              
              idper[intcontador]=Even.getId_eve();
              columna[0]=String.valueOf(Even.getId_eve());
              columna[1]=Even.getTitulo_eve();              
               modelo.addElement(Even.getTitulo_eve());
               intcontador ++;
          }
          cboeventos.setModel(modelo);
     }
    
    private void txtFiltroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFiltroKeyTyped
        // TODO add your handling code here:
//
//        txtFiltro.addKeyListener(new KeyAdapter() {
//            @Override
//            public void keyReleased(KeyEvent ke) {
//                trs.setRowFilter(RowFilter.regexFilter("(?i)"+leerBusqueda(), 0,1,2,3,4,5,6)); //Filtra datos
//            }
//        });
//        trs=new TableRowSorter(dtm);
//        tblEstudiante.setRowSorter(trs);
    }//GEN-LAST:event_txtFiltroKeyTyped

    private void cboeventosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboeventosActionPerformed
        // TODO add your handling code here:
        
        
         ClsNegAsistentes estudi =new ClsNegAsistentes();     
        
        ArrayList<ClsEntAsistentes> EStu=estudi.ListarAsistenesPorEvento2(idper[cboeventos.getSelectedIndex()]);
     
       //  JOptionPane.showMessageDialog(null,idper4[cbo2.getSelectedIndex()]);
        Iterator iterator1=EStu.iterator();
      
           String titulo5[]={"codigo","nombre","hora entrada","hora salida","Escuela"};
          DefaultTableModel dtm5=new DefaultTableModel(null,titulo5);
        String columna2[]=new String[5];
        while (iterator1.hasNext()) {
            ClsEntAsistentes ES=new ClsEntAsistentes();
            ES=(ClsEntAsistentes) iterator1.next();
            columna2[0]=String.valueOf(ES.getCodigo_estu());               
             columna2[1]=ES.getNombre_estu();
            columna2[2]=ES.getHora_entrada(); 
              columna2[3]=ES.getHora_salida0(); 
             columna2[4]=ES.getNombre_escu(); 
           
               dtm5.addRow(columna2);            
        }    
        
         tblAsistentes.setModel(dtm5); 
    }//GEN-LAST:event_cboeventosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboeventos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAsistentes;
    private rscomponentshade.RSFormatFieldShade txtFiltro;
    // End of variables declaration//GEN-END:variables
}
