/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import principal.Principal;

/**
 *
 * @author RojeruSan
 */
public class pnlMantenimiento extends javax.swing.JPanel {

    /**
     * Creates new form pnlHome
     */
    public pnlMantenimiento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        btnCancelar = new rscomponentshade.RSButtonShade();
        btnCancelar1 = new rscomponentshade.RSButtonShade();
        btnCancelar2 = new rscomponentshade.RSButtonShade();
        btnCancelar3 = new rscomponentshade.RSButtonShade();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("jMenu3");

        setBackground(new java.awt.Color(204, 204, 204));

        btnCancelar.setBackground(new java.awt.Color(51, 51, 51));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icono-menu.png"))); // NOI18N
        btnCancelar.setText("Facultad");
        btnCancelar.setBgHover(new java.awt.Color(10, 36, 95));
        btnCancelar.setBgShade(new java.awt.Color(255, 255, 255));
        btnCancelar.setBgShadeHover(new java.awt.Color(242, 187, 10));
        btnCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnCancelar1.setBackground(new java.awt.Color(51, 51, 51));
        btnCancelar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icono-menu.png"))); // NOI18N
        btnCancelar1.setText("Escuela ");
        btnCancelar1.setBgHover(new java.awt.Color(10, 36, 95));
        btnCancelar1.setBgShade(new java.awt.Color(255, 255, 255));
        btnCancelar1.setBgShadeHover(new java.awt.Color(242, 187, 10));
        btnCancelar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancelar1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelar1ActionPerformed(evt);
            }
        });

        btnCancelar2.setBackground(new java.awt.Color(51, 51, 51));
        btnCancelar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icono-menu.png"))); // NOI18N
        btnCancelar2.setText("Modalidad Ingreso");
        btnCancelar2.setBgHover(new java.awt.Color(10, 36, 95));
        btnCancelar2.setBgShade(new java.awt.Color(255, 255, 255));
        btnCancelar2.setBgShadeHover(new java.awt.Color(242, 187, 10));
        btnCancelar2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancelar2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCancelar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelar2ActionPerformed(evt);
            }
        });

        btnCancelar3.setBackground(new java.awt.Color(51, 51, 51));
        btnCancelar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icono-menu.png"))); // NOI18N
        btnCancelar3.setText("Convocatoria");
        btnCancelar3.setBgHover(new java.awt.Color(10, 36, 95));
        btnCancelar3.setBgShade(new java.awt.Color(255, 255, 255));
        btnCancelar3.setBgShadeHover(new java.awt.Color(242, 187, 10));
        btnCancelar3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancelar3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCancelar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelar3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCancelar2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCancelar3, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnCancelar3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelar2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelar1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(402, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        new CambiaPanel(Principal.pnlPrincipal, new paneles.pnlFacultad());
        Principal.lblTitulo.setText("   Mantenimiento Facultad");
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelar1ActionPerformed
        new CambiaPanel(Principal.pnlPrincipal, new paneles.pnlEscuela());
        Principal.lblTitulo.setText("   Mantenimiento Escuela");
    }//GEN-LAST:event_btnCancelar1ActionPerformed

    private void btnCancelar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelar2ActionPerformed
        new CambiaPanel(Principal.pnlPrincipal, new paneles.pnlModalidadIngreso());
        Principal.lblTitulo.setText("   Mantenimiento Modalidad Ingreso");
    }//GEN-LAST:event_btnCancelar2ActionPerformed

    private void btnCancelar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelar3ActionPerformed
        new CambiaPanel(Principal.pnlPrincipal, new paneles.pnlConvocatoria());
        Principal.lblTitulo.setText("   Mantenimiento Convocatoria");
    }//GEN-LAST:event_btnCancelar3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rscomponentshade.RSButtonShade btnCancelar;
    private rscomponentshade.RSButtonShade btnCancelar1;
    private rscomponentshade.RSButtonShade btnCancelar2;
    private rscomponentshade.RSButtonShade btnCancelar3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
